// TEORIA: tarjetas de conceptos y teoría. Reemplazá este archivo con el código generado.
// Formato: {cat:"Categoría", d:"Descripción o concepto", t:"Término"}
const TEORIA = [
// ===== Rol del estudiante =====
{cat:"Rol del estudiante", d:"Símbolo de higiene y respeto institucional que introduce cierta desigualdad en la relación con el paciente, algo propio del ámbito médico.", t:"Guardapolvo"},
{cat:"Rol del estudiante", d:"Lo primero que debe hacer el estudiante ante el paciente: aclarar su rol (ej.: \"soy estudiante de medicina\") y evitar hacerse pasar por médico.", t:"Presentarse como estudiante"},
{cat:"Rol del estudiante", d:"Qué debe hacer el estudiante si el paciente se niega a ser entrevistado.", t:"Respetar la negativa del paciente"},
{cat:"Rol del estudiante", d:"Conducta del estudiante en etapas iniciales ante preguntas del paciente sobre diagnóstico o tratamiento: no responderlas y derivarlas al médico responsable.", t:"Derivar las preguntas médicas"},
{cat:"Rol del estudiante", d:"Estrategia más adecuada ante el llanto o el enojo del paciente (ej.: \"Puedo ver que está muy angustiado\" / \"Esta conversación parece irritarlo\"). No se debe confrontar ni retirarse.", t:"Reflexión y legitimación de la emoción"},
{cat:"Rol del estudiante", d:"Qué debe hacer el estudiante si el paciente revela una idea suicida: comunicarlo al médico a cargo; no alcanza con sugerirle al paciente que lo haga.", t:"Obligación de informar situaciones graves"},
{cat:"Rol del estudiante", d:"Lo que el estudiante nunca debe prometer al paciente; debe explicar que puede necesitar compartir información relevante con su supervisor o el equipo.", t:"Secreto absoluto"},
{cat:"Rol del estudiante", d:"Riesgo del contacto físico inadecuado del estudiante con el paciente.", t:"Dependencia emocional"},
{cat:"Rol del estudiante", d:"Calificación que recibe toda relación sexual entre médico y paciente.", t:"Abuso de poder"},
{cat:"Rol del estudiante", d:"Motivo por el cual muchos pacientes aceptan hablar con los estudiantes: encuentran satisfacción en ayudar a la formación médica, lo que puede mejorar su adaptación a la enfermedad.", t:"Satisfacción altruista del paciente"},

// ===== Entrevista clínica =====
{cat:"Entrevista clínica", d:"Clásica definición de la entrevista médica: \"el encuentro entre una confianza y una conciencia\".", t:"Entrevista médica"},
{cat:"Entrevista clínica", d:"Tres funciones principales de la entrevista: recopilar datos, construir rapport y educar y motivar (favorecer la adherencia).", t:"Funciones de la entrevista médica"},
{cat:"Entrevista clínica", d:"Comprender la situación emocional del paciente, aceptarla, reconocerlo como un igual y experimentar objetivamente lo que siente.", t:"Empatía (definición en la entrevista)"},
{cat:"Entrevista clínica", d:"Comunicación no verbal en la entrevista: contacto visual directo (evitarlo en pacientes paranoicos), postura de atención y uso adecuado del espacio.", t:"Habilidades no verbales"},
{cat:"Entrevista clínica", d:"Técnica verbal no directiva que permite al paciente expresarse con su propio lenguaje (ej.: \"¿Qué problemas lo trajeron?\").", t:"Preguntas abiertas"},
{cat:"Entrevista clínica", d:"Técnica verbal para animar al paciente a continuar (ej.: \"Dígame más…\" y silencios atentos).", t:"Facilitación"},
{cat:"Entrevista clínica", d:"Técnica verbal de interrupciones breves para ordenar los datos del relato.", t:"Aclaración y dirección"},
{cat:"Entrevista clínica", d:"Técnica verbal de resumir lo entendido para verificar la comprensión; se la considera la regla cardinal ante la duda.", t:"Comprobación (chequeo)"},
{cat:"Entrevista clínica", d:"Técnica verbal que consiste en repetir \"¿Qué más le molesta?\" hasta completar el panorama; no quedarse con el primer problema.", t:"Indagación exhaustiva"},
{cat:"Entrevista clínica", d:"Primer paso de la apertura de la entrevista: saludo no verbal (mirada, apretón de manos) y presentación con nombre y rol.", t:"Introducción"},
{cat:"Entrevista clínica", d:"Paso de la apertura en el que se explica el propósito de la entrevista y se negocian los objetivos si difieren de los del paciente.", t:"Establecer objetivos"},
{cat:"Entrevista clínica", d:"Paso de la apertura que es obligatorio en estudiantes: debe ser verbal, explícito y respetar la negativa del paciente.", t:"Obtener consentimiento"},
{cat:"Entrevista clínica", d:"Etapa más importante de la apertura de la entrevista: mostrar interés genuino por la persona y responder de inmediato a sus emociones.", t:"Establecer rapport"},
{cat:"Entrevista clínica", d:"Paso de la apertura en el que se evalúa el estado actual del paciente (\"¿Cómo se siente ahora?\") y se ajusta el entorno (dolor, temperatura, etc.).", t:"Establecer confort del paciente"},
{cat:"Entrevista clínica", d:"Tres preguntas de cierre de la entrevista: qué es lo que más le preocupa, en qué o en quién se sostiene y si quiere agregar algo más.", t:"Preguntas de cierre"},
{cat:"Entrevista clínica", d:"Uso de dos registros en la entrevista: lenguaje común para comunicarse con el paciente y lenguaje técnico para el registro clínico.", t:"Doble registro"},
{cat:"Entrevista clínica", d:"Error de la entrevista que impide percibir la emocionalidad y aleja la confianza del paciente: hacerla como una lista de verificación rígida.", t:"Entrevista como \"checklist\""},
{cat:"Entrevista clínica", d:"Ejemplo de lenguaje claro: preguntar \"¿Lo han operado?\" en lugar de \"¿Cuáles son sus antecedentes quirúrgicos?\".", t:"Evitar tecnicismos"},
{cat:"Entrevista clínica", d:"Ejemplo de pregunta que facilita que el paciente narre su historia: \"¿Cómo se alimenta?\" en lugar de \"¿Come de todo?\".", t:"Pregunta abierta vs. cerrada"},
{cat:"Entrevista clínica", d:"Errores a evitar en la entrevista: mostrar apuro (mirar el reloj), interrumpir el relato inicial y emitir juicios de valor.", t:"Errores en la entrevista"},
{cat:"Entrevista clínica", d:"Sistema de la historia clínica que se explora con síntomas no referidos espontáneamente por el paciente (aplicable desde tercer año).", t:"Revisión por sistemas"},

// ===== Historia clínica =====
{cat:"Historia clínica", d:"Instrumento clínico y médico-legal que permite comprender al paciente de manera integral; es una construcción ordenada, lógica y cronológica y no solo una acumulación de datos.", t:"Historia clínica"},
{cat:"Historia clínica", d:"Funciones de la historia clínica: asistencial, docente e investigativa, y médico-legal.", t:"Funciones de la historia clínica"},
{cat:"Historia clínica", d:"Principio de la historia clínica: registrar los hechos diferenciando lo que refiere el paciente de lo que observa el médico, sin juicios de valor.", t:"Veracidad y objetividad"},
{cat:"Historia clínica", d:"Datos que identifican al paciente: nombre, edad, fecha de nacimiento, domicilio, nacionalidad, estado civil, ocupación y religión.", t:"Datos de filiación"},
{cat:"Historia clínica", d:"Queja principal del paciente, registrada con sus palabras textuales y entre comillas, sin interpretarla ni traducirla al lenguaje médico.", t:"Motivo de consulta"},
{cat:"Historia clínica", d:"Parte medular de la historia clínica: relato cronológico, ordenado y detallado que construye un hilo narrativo.", t:"Enfermedad actual"},
{cat:"Historia clínica", d:"Secuencia cronológica que conecta el inicio del problema, su evolución y el contexto en que aparece.", t:"Hilo narrativo"},
{cat:"Historia clínica", d:"Siete atributos de un síntoma: localización, cualidad, severidad (1–10), temporalidad, contexto, factores modificantes y síntomas asociados.", t:"Atributos del síntoma"},
{cat:"Historia clínica", d:"Pregunta clave para comprender qué cree el paciente que tiene y a qué lo atribuye; permite entender su conducta y mejora la adherencia.", t:"Modelo explicativo del paciente"},
{cat:"Historia clínica", d:"Aspectos de la vida del paciente que deben evaluarse para medir el impacto de la enfermedad: relaciones interpersonales, trabajo, vida sexual y estado emocional.", t:"Impacto en la calidad de vida"},
{cat:"Historia clínica", d:"Antecedentes personales que incluyen edad gestacional, peso, parto, Apgar y neonatología.", t:"Antecedentes perinatales"},
{cat:"Historia clínica", d:"Antecedentes que evalúan hitos como lenguaje, motricidad y socialización (sonrisa social, sostén cefálico, gateo, control de esfínteres).", t:"Desarrollo psicomotor"},
{cat:"Historia clínica", d:"Puntaje que mide la vitalidad del recién nacido.", t:"Score de Apgar"},
{cat:"Historia clínica", d:"Detección neonatal de enfermedades como fibrosis quística o hipotiroidismo.", t:"Pesquisa neonatal"},
{cat:"Historia clínica", d:"Hábitos que incluyen alimentación, sueño, diuresis, catarsis y actividad física.", t:"Hábitos fisiológicos"},
{cat:"Historia clínica", d:"Hábitos que incluyen tabaco, alcohol, drogas y automedicación.", t:"Hábitos tóxicos"},
{cat:"Historia clínica", d:"Antecedentes de menarca, ciclos, relaciones sexuales, anticoncepción, FUM, embarazos, partos y abortos.", t:"Antecedentes gineco-obstétricos"},
{cat:"Historia clínica", d:"Antecedentes que incluyen enfermedades, cirugías, traumatismos, internaciones y alergias (describiendo la reacción).", t:"Antecedentes médicos y quirúrgicos"},
{cat:"Historia clínica", d:"Antecedentes sobre la salud de los familiares, con representación gráfica de la genealogía.", t:"Antecedentes heredofamiliares"},
{cat:"Historia clínica", d:"Antecedentes que incluyen vivienda, trabajo, servicios, contaminación y mascotas.", t:"Antecedentes socioambientales"},
{cat:"Historia clínica", d:"Parte de la historia clínica que detalla ocupación actual y anteriores, tiempo de exposición a polvos, químicos, ruidos o radiación, y uso de equipo de protección.", t:"Historia ocupacional y ambiental"},
{cat:"Historia clínica", d:"Registro que solo se detalla si la información proviene de un tercero o si la confiabilidad del paciente está comprometida (confusión, demencia, hostilidad, psicosis).", t:"Origen y credibilidad de la información"},
{cat:"Historia clínica", d:"Cómo se recomienda presentar varios problemas en la enfermedad actual: jerarquizarlos y titularlos por separado (ej.: 1. Disuria, 2. Homalgia).", t:"Jerarquizar los problemas"},
{cat:"Historia clínica", d:"Datos objetivos obtenidos mediante inspección, palpación, percusión y auscultación; siempre se registran los signos vitales (TA, FC, FR, temperatura y saturación de oxígeno).", t:"Examen físico"},
{cat:"Historia clínica", d:"Hipótesis diagnóstica que se formula a partir del interrogatorio y el examen físico.", t:"Diagnóstico presuntivo"},
{cat:"Historia clínica", d:"Resumen final de la historia clínica, que sintetiza el caso hasta el diagnóstico definitivo.", t:"Epicrisis"},
{cat:"Historia clínica", d:"Orden de la historia clínica: filiación, motivo de consulta, enfermedad actual, modelo explicativo, antecedentes, examen físico, diagnóstico presuntivo, estudios, evolución y tratamiento, epicrisis.", t:"Esquema de la historia clínica"},
{cat:"Historia clínica", d:"Componentes de la información clínica: datos (subjetivos y objetivos), evaluación (opiniones médicas, impresiones diagnósticas) y planes (diagnóstico, tratamiento y educación).", t:"Datos, evaluación y planes"},
{cat:"Historia clínica", d:"Tiempo mínimo que las instituciones deben conservar la historia clínica, según la Ley 26.529.", t:"10 años"},

// ===== Relación médico-paciente =====
{cat:"Relación médico-paciente", d:"Modelo de relación en el que predomina la actividad del médico y la pasividad del paciente (coma, urgencias, cirugía); su analogía es el vínculo madre–lactante.", t:"Hollender nivel 1: actividad–pasividad"},
{cat:"Relación médico-paciente", d:"Modelo de relación más frecuente en la práctica clínica: el médico dirige y el paciente coopera; se asemeja al vínculo padres–hijo.", t:"Hollender nivel 2: dirección–cooperación"},
{cat:"Relación médico-paciente", d:"Modelo de relación típico de enfermedades crónicas, rehabilitación y salud mental: vínculo adulto–adulto con decisiones compartidas.", t:"Hollender nivel 3: participación mutua"},
{cat:"Relación médico-paciente", d:"Competencia central del médico según el modelo de Hollender: adaptarse con flexibilidad a cada momento clínico, ya que un mismo paciente puede transitar por los tres niveles.", t:"Flexibilidad entre niveles"},
{cat:"Relación médico-paciente", d:"Distinción entre lo que el enfermo siente (vivencia subjetiva) y lo que el enfermo tiene (proceso patológico detectable por el médico).", t:"Illness vs. disease"},
{cat:"Relación médico-paciente", d:"Forma en que la enfermedad se expresa en la biografía (Muratorio Posse): hecho que irrumpe y distorsiona la historia personal.", t:"Enfermedad como accidente"},
{cat:"Relación médico-paciente", d:"Forma en que la enfermedad se expresa en la biografía: permite enfrentar la fragilidad propia y, a veces, adoptar hábitos más sanos al recibir atención preferencial.", t:"Enfermedad como beneficio"},
{cat:"Relación médico-paciente", d:"Forma en que la enfermedad se expresa en la biografía: un \"búnker\" para escapar de circunstancias externas amenazantes.", t:"Enfermedad como refugio"},
{cat:"Relación médico-paciente", d:"Forma en que la enfermedad se expresa en la biografía: recurso para adquirir importancia y ser el centro de atención del entorno social.", t:"Enfermedad como emblema"},
{cat:"Relación médico-paciente", d:"Construcción del paciente sobre su malestar basada en su cultura, biografía y emociones (ej.: \"se me taparon las venas\"); reduce la incertidumbre.", t:"Teoría subjetiva (modelo explicativo)"},
{cat:"Relación médico-paciente", d:"Imagen de Woolf para el enfermo, que se detiene mientras el mundo sigue marchando; la enfermedad como retiro del mandato de producir.", t:"Enfermo como \"desertor\" de la armada de los sanos"},
{cat:"Relación médico-paciente", d:"Imagen de Solzhenitsyn del impacto de la enfermedad: cierra la vida pasada y reduce al sujeto a un cuerpo objeto de observación.", t:"Enfermedad como \"portazo\""},
{cat:"Relación médico-paciente", d:"Metáfora de Trillin para el ingreso a la enfermedad grave: todo parece igual pero cambia la mirada de los otros, lo que genera alienación y soledad.", t:"\"La tierra de la gente enferma\""},
{cat:"Relación médico-paciente", d:"Según el texto, lo que verdaderamente conecta a médicos y pacientes más allá de los roles.", t:"Miedo a la muerte"},
{cat:"Relación médico-paciente", d:"Ilusión de inmortalidad con la que las personas sanas se distancian del enfermo para negar su propia vulnerabilidad; permite funcionar pero dificulta la comunicación auténtica.", t:"\"Fraude necesario\""},
{cat:"Relación médico-paciente", d:"Acuerdo implícito en el que el médico representa el poder de curar; los mejores profesionales lo comparten con información clara. Si falla, el médico es visto como un \"mago fallido\".", t:"\"Magia de la medicina\""},
{cat:"Relación médico-paciente", d:"Mecanismo de defensa por el cual mantener vivo al paciente es desafiar a la muerte; si el tratamiento fracasa pueden surgir frustración, enojo o culpabilización del paciente.", t:"Paciente como talismán del médico"},
{cat:"Relación médico-paciente", d:"Narrativa de lucha que sostiene emocionalmente al paciente, pero con el riesgo de que empeorar se viva como un fracaso personal o moral.", t:"\"Acto guerrero\""},
{cat:"Relación médico-paciente", d:"Metáfora del retorno a lo cotidiano (interesarse otra vez por algo trivial) como forma de reafirmar la vida frente a la muerte.", t:"Las \"arvejas del huerto\""},
{cat:"Relación médico-paciente", d:"Imagen final del texto: no se lo derrota definitivamente, pero se lo mantiene a distancia mientras se sigue viviendo.", t:"El \"dragón\""},
{cat:"Relación médico-paciente", d:"Caso de un hombre con crisis asmáticas coincidentes con campañas electorales, cuyo hijo desaparecido durante la dictadura se llamaba como la palabra aymará para \"aire\".", t:"Caso Padrón (Huayra)"},
{cat:"Relación médico-paciente", d:"Enseñanza del caso Padrón: permitir que el paciente hable y llore es clave para entender el origen del síntoma.", t:"Clínica de la ausencia"},
{cat:"Relación médico-paciente", d:"Tres dimensiones de la práctica médica: conocimientos teóricos, capacidad de aplicarlos de manera individualizada y reconocimiento de la dignidad del paciente.", t:"Ciencia, artesanía y humanismo"},
{cat:"Relación médico-paciente", d:"Habilidades técnicas de la formación médica: conocimientos científicos, procedimientos, diagnóstico y manejo clínico.", t:"Hard skills"},
{cat:"Relación médico-paciente", d:"Habilidades humanas de la formación médica: empatía, comunicación, liderazgo, trabajo en equipo y actitud compasiva.", t:"Soft skills"},
{cat:"Relación médico-paciente", d:"Tres pilares de una medicina humanizada: empatía, ética y capacidad de construir un vínculo de confianza.", t:"Pilares de la medicina humanizada"},
{cat:"Relación médico-paciente", d:"Síndrome caracterizado por agotamiento emocional, despersonalización y baja realización profesional.", t:"Síndrome de burnout"},
{cat:"Relación médico-paciente", d:"Medidas de prevención del burnout: manejo del estrés, fomento de la empatía, tutorías y mejores condiciones laborales.", t:"Prevención del burnout"},
{cat:"Relación médico-paciente", d:"Barrera frecuente: los médicos omiten más del 50% de las preocupaciones del paciente, por priorizar lo biomédico o por temor a las emociones intensas.", t:"Barreras de comunicación del médico"},
{cat:"Relación médico-paciente", d:"Error de comunicación: afirmar que \"no hay cura\", lo que transmite desesperanza e ignora que el médico siempre puede ayudar.", t:"Mensajes desalentadores"},
{cat:"Relación médico-paciente", d:"Error ético: garantizar la curación; el compromiso del médico debe centrarse en los medios y el esfuerzo terapéutico.", t:"Promesas poco éticas"},
{cat:"Relación médico-paciente", d:"Error ético: usar el miedo (por ejemplo, \"amenazar con cáncer\") como herramienta de persuasión.", t:"Uso del miedo como persuasión"},
{cat:"Relación médico-paciente", d:"Error que vulnera el secreto profesional: hablar de otros pacientes o compararlos; es una falta ética e incluso un delito.", t:"Indiscreción"},
{cat:"Relación médico-paciente", d:"Error en el trato: tratar al paciente como a un niño, limitando su autonomía, o proyectar frustraciones en pacientes crónicos.", t:"Deshumanización del trato"},

// ===== Empatía y emociones =====
{cat:"Empatía y emociones", d:"Estrategia de respuesta emocional: informar al paciente las emociones observadas (ej.: \"Parece algo triste\"), usando al inicio terminología poco amenazante.", t:"Reflexión"},
{cat:"Empatía y emociones", d:"Estrategia de respuesta emocional: comunicar que los sentimientos son comprensibles y normales dadas las circunstancias (ej.: \"Cualquiera encontraría esto difícil\"), incluso sin acordar con las razones.", t:"Legitimación"},
{cat:"Empatía y emociones", d:"Estrategia de respuesta emocional: expresar honestamente el deseo de ayudar (ej.: \"Quiero ayudarle en la forma que pueda\").", t:"Respaldo personal"},
{cat:"Empatía y emociones", d:"Estrategia de respuesta emocional que fomenta la sensación de trabajo en equipo (ej.: \"Trabajemos juntos en un plan\").", t:"Compañía"},
{cat:"Empatía y emociones", d:"Estrategia de respuesta emocional: valorar explícitamente cómo el paciente enfrenta su situación (ej.: \"Estoy impresionado por cómo maneja esta incertidumbre\").", t:"Respeto"},
{cat:"Empatía y emociones", d:"Responder a los sentimientos del paciente tan pronto como se presentan; ignorarlos puede interpretarse como miedo o falta de interés.", t:"Regla cardenal (Cohen-Cole)"},
{cat:"Empatía y emociones", d:"Conductas como postura, gestos, tono de voz, velocidad del discurso y tacto, a menudo más determinantes que las palabras para transmitir calidez e interés.", t:"Estrategias no verbales"},
{cat:"Empatía y emociones", d:"Habilidad aprendible, no un rasgo innato: comprensión del mundo del paciente y capacidad de comunicar lo comprendido.", t:"Empatía clínica"},
{cat:"Empatía y emociones", d:"Dimensiones de la empatía: emocional (sentir con el otro), cognitiva (entender creencias), física (comunicación corporal) e imaginativa (\"¿y si fuera yo?\").", t:"Dimensiones de la empatía"},
{cat:"Empatía y emociones", d:"Pilares de la conexión genuina: suspender el juicio, ausencia de crítica y eliminar la culpa.", t:"Pilares de la empatía"},
{cat:"Empatía y emociones", d:"Primer paso del entrenamiento en empatía: enfoque total en la persona, eliminando distracciones como el celular.", t:"Estar presente"},
{cat:"Empatía y emociones", d:"Paso del entrenamiento en empatía: recibir la experiencia ajena sin minimizar; evitar frases como \"no se preocupe\" o \"no es para tanto\".", t:"Apertura"},
{cat:"Empatía y emociones", d:"Paso del entrenamiento en empatía: mantener el equilibrio emocional para ayudar sin contagiarse del sufrimiento del paciente.", t:"Serenidad"},
{cat:"Empatía y emociones", d:"Paso del entrenamiento en empatía: comunicar la empatía con preguntas de interés y lenguaje no verbal adecuado.", t:"Expresión"},
{cat:"Empatía y emociones", d:"Herramienta de comunicación que consiste en hacer resúmenes periódicos para verificar la comprensión mutua.", t:"Resumen de verificación"},
{cat:"Empatía y emociones", d:"Herramienta de comunicación: adaptar el lenguaje al nivel del interlocutor, usar ejemplos y verificar la recepción con preguntas específicas.", t:"Información"},
{cat:"Empatía y emociones", d:"Herramienta de comunicación: empatía verbal y no verbal, validando emociones y temores sin emitir juicios de valor.", t:"Contención"},

// ===== Entrevista motivacional =====
{cat:"Entrevista motivacional", d:"Prevención que actúa sobre las causas antes de la aparición de la enfermedad.", t:"Prevención primaria"},
{cat:"Entrevista motivacional", d:"Prevención centrada en la detección y el tratamiento en fases precoces.", t:"Prevención secundaria"},
{cat:"Entrevista motivacional", d:"Prevención que aborda las consecuencias de la enfermedad y busca reducir la incapacidad (rehabilitación).", t:"Prevención terciaria"},
{cat:"Entrevista motivacional", d:"Proceso que permite a las personas incrementar el control sobre su salud para mejorarla, definido por la Carta de Ottawa (1986).", t:"Promoción de la salud"},
{cat:"Entrevista motivacional", d:"Proceso por el cual el individuo adquiere mayor capacidad de decidir y ejercer control sobre los aspectos que afectan su vida y su salud.", t:"Empoderamiento"},
{cat:"Entrevista motivacional", d:"Forma de abordar la resistencia al cambio: aplicar el criterio profesional de manera unidireccional.", t:"Imposición"},
{cat:"Entrevista motivacional", d:"Forma de abordar la resistencia al cambio: intentar convencer al paciente con la intención de buscar su beneficio.", t:"Influencia"},
{cat:"Entrevista motivacional", d:"Forma de abordar la resistencia al cambio: brindar información sesgada para inducir una decisión; es éticamente inaceptable.", t:"Manipulación"},
{cat:"Entrevista motivacional", d:"Forma de abordar la resistencia al cambio: alcanzar acuerdos mediante el diálogo y el pacto, reconociendo la autonomía del paciente.", t:"Negociación"},
{cat:"Entrevista motivacional", d:"Habilidad comunicacional: favorecer que el paciente exprese sus conocimientos, opiniones y experiencias.", t:"Bidireccionalidad"},
{cat:"Entrevista motivacional", d:"Habilidad comunicacional: transmitir cercanía, principalmente mediante la comunicación no verbal.", t:"Calidez"},
{cat:"Entrevista motivacional", d:"Habilidad comunicacional: respetar las opiniones del paciente manteniendo las propias.", t:"Asertividad"},
{cat:"Entrevista motivacional", d:"Habilidad comunicacional: escuchar sin interrumpir ni responder de manera defensiva ante las resistencias.", t:"Baja reactividad"},
{cat:"Entrevista motivacional", d:"Método clínico colaborativo y centrado en la persona cuyo objetivo es evocar y fortalecer la motivación propia del paciente para el cambio.", t:"Entrevista motivacional"},
{cat:"Entrevista motivacional", d:"Principio de la entrevista motivacional: evitar decirle directamente al paciente qué debería hacer.", t:"Inhibir el reflejo de redirección"},
{cat:"Entrevista motivacional", d:"Principio de la entrevista motivacional: comprender que una misma persona puede tener razones para cambiar y razones para mantener una conducta.", t:"Explorar la ambivalencia"},
{cat:"Entrevista motivacional", d:"Herramienta central de la entrevista motivacional: devolver al paciente elementos de su propio discurso para favorecer la reflexión.", t:"Escucha reflexiva"},
{cat:"Entrevista motivacional", d:"Nivel de escucha reflexiva: reproducir literalmente lo expresado por el paciente.", t:"Repetir"},
{cat:"Entrevista motivacional", d:"Nivel de escucha reflexiva: expresar la misma idea con otras palabras.", t:"Refrasear"},
{cat:"Entrevista motivacional", d:"Nivel de escucha reflexiva: reformular el contenido infiriendo su significado.", t:"Parafrasear"},
{cat:"Entrevista motivacional", d:"Nivel más profundo de escucha reflexiva: identificar y devolver la emoción que subyace al discurso.", t:"Reflexión de sentimientos"},
{cat:"Entrevista motivacional", d:"Resúmenes estratégicos que organizan la información del paciente, demuestran escucha atenta y facilitan pasar a la siguiente etapa de la entrevista.", t:"Sumarios"},
{cat:"Entrevista motivacional", d:"Secuencia para dar información o aconsejar: pedir permiso y explorar qué desea saber el paciente, ofrecer la información y verificar cómo fue comprendida.", t:"Preguntar–Informar–Comprobar"},

// ===== Genealogía clínica =====
{cat:"Genealogía clínica", d:"Representación gráfica con enfoque biopsicosocial de la familia (estructura, ciclo vital, vínculos); es una \"fotografía\" de un momento determinado y puede perder vigencia.", t:"Genograma (familiograma)"},
{cat:"Genealogía clínica", d:"Representación gráfica de la transmisión de rasgos o enfermedades en una familia biológicamente relacionada; tiene carácter más permanente y busca reconocer patrones de herencia.", t:"Árbol genealógico (pedigrí o linaje)"},
{cat:"Genealogía clínica", d:"Por qué se considera al árbol genealógico el \"primer test genético\" de la medicina de precisión: aporta mucha información diagnóstica y preventiva de forma simple y económica.", t:"Árbol genealógico como primer test genético"},
{cat:"Genealogía clínica", d:"Cantidad mínima de generaciones que se recomienda incluir en un árbol genealógico para identificar patrones hereditarios.", t:"Tres o cuatro generaciones"},
{cat:"Genealogía clínica", d:"Las generaciones se designan con números romanos y los integrantes con números arábigos de izquierda a derecha (ej.: III-2 es el segundo individuo de la tercera generación).", t:"Nomenclatura generacional"},
{cat:"Genealogía clínica", d:"Individuo afectado cuya condición motiva el estudio familiar; se señala con una flecha o doble línea alrededor del símbolo.", t:"Caso índice (probando)"},
{cat:"Genealogía clínica", d:"Persona que solicita el asesoramiento médico o genético; puede estar sana o afectada y se representa solo con una flecha.", t:"Consultante"},
{cat:"Genealogía clínica", d:"Símbolo del hombre en la simbología genealógica internacional.", t:"Cuadrado"},
{cat:"Genealogía clínica", d:"Símbolo de la mujer en la simbología genealógica internacional.", t:"Círculo"},
{cat:"Genealogía clínica", d:"Símbolo de sexo desconocido en la simbología genealógica internacional.", t:"Rombo"},
{cat:"Genealogía clínica", d:"Cómo se representa a un individuo afectado en el árbol genealógico.", t:"Símbolo relleno"},
{cat:"Genealogía clínica", d:"Cómo se representa a un individuo fallecido en el árbol genealógico (se agrega edad y causa de muerte).", t:"Línea diagonal o \"X\""},
{cat:"Genealogía clínica", d:"Representación de la pareja en el árbol: matrimonio.", t:"Línea continua"},
{cat:"Genealogía clínica", d:"Representación de la pareja en el árbol: unión libre.", t:"Línea punteada"},
{cat:"Genealogía clínica", d:"Representación de la pareja en el árbol: separación.", t:"Una línea diagonal"},
{cat:"Genealogía clínica", d:"Representación de la pareja en el árbol: divorcio.", t:"Dos líneas diagonales"},
{cat:"Genealogía clínica", d:"Cómo se representan los gemelos monocigóticos: parten de un mismo punto y se unen además por una línea horizontal.", t:"Gemelos monocigóticos"},
{cat:"Genealogía clínica", d:"Cómo se representa al individuo adoptado: entre corchetes, con línea punteada hacia los padres adoptivos y continua hacia los biológicos si se conocen.", t:"Adopción"},
{cat:"Genealogía clínica", d:"Cómo se representa el embarazo actual en el árbol genealógico.", t:"Triángulo"},
{cat:"Genealogía clínica", d:"Cómo se representa un aborto espontáneo en el árbol genealógico.", t:"Círculo pequeño negro"},
{cat:"Genealogía clínica", d:"Cómo se representa un aborto inducido en el árbol genealógico.", t:"Círculo pequeño con \"X\""},
{cat:"Genealogía clínica", d:"Cómo se representa una muerte fetal en el árbol genealógico.", t:"Símbolo sexual con \"X\""},
{cat:"Genealogía clínica", d:"Letras usadas en reproducción asistida: D (donante de gametos) y S (gestante subrogada).", t:"D y S en reproducción asistida"},
{cat:"Genealogía clínica", d:"Término que se refiere a cualquier alteración en el ADN; puede ser somática o germinal.", t:"Genético"},
{cat:"Genealogía clínica", d:"Alteración genética que afecta determinadas células y no se hereda.", t:"Alteración somática"},
{cat:"Genealogía clínica", d:"Alteración genética presente en gametas y transmisible a la descendencia.", t:"Alteración germinal"},
{cat:"Genealogía clínica", d:"Alteraciones genéticas capaces de transmitirse entre generaciones.", t:"Hereditario"},
{cat:"Genealogía clínica", d:"Condición presente desde el nacimiento, independientemente de su causa (genética, infecciones intrauterinas, hipoxia fetal o sustancias tóxicas).", t:"Congénito"},
{cat:"Genealogía clínica", d:"Unión entre familiares que aumenta la probabilidad de homocigosis para genes recesivos y el riesgo de enfermedades hereditarias.", t:"Consanguinidad"},
{cat:"Genealogía clínica", d:"Individuo que necesariamente porta la mutación aunque no manifieste síntomas; se representa con un punto central.", t:"Portador obligatorio"},
{cat:"Genealogía clínica", d:"Persona que aún no desarrolla la enfermedad por la edad o por penetrancia incompleta; se representa con una línea vertical central.", t:"Portador presintomático"},
{cat:"Genealogía clínica", d:"Herencia que afecta a ambos sexos, aparece en todas las generaciones, con transmisión vertical y riesgo aproximado del 50% si un progenitor está afectado.", t:"Herencia autosómica dominante"},
{cat:"Genealogía clínica", d:"Herencia que afecta por igual a hombres y mujeres, puede \"saltar\" generaciones, con padres portadores sanos y riesgo del 25% en cada embarazo.", t:"Herencia autosómica recesiva"},
{cat:"Genealogía clínica", d:"Herencia que predomina en varones, se transmite generalmente por madres portadoras y los hombres afectados no la transmiten a sus hijos varones.", t:"Herencia ligada al cromosoma X recesiva"},
{cat:"Genealogía clínica", d:"Recomendaciones de privacidad para el árbol genealógico: usar iniciales en lugar de nombres, años de nacimiento en vez de fechas exactas y cumplir normas de protección de datos.", t:"Confidencialidad del árbol genealógico"},

// ===== Salud pública =====
{cat:"Salud pública", d:"Modelo tradicional centrado exclusivamente en la enfermedad como alteración biológica o bioquímica.", t:"Modelo biomédico"},
{cat:"Salud pública", d:"Modelo propuesto por George Engel en 1977: salud y enfermedad resultan de la interacción de factores biológicos, psicológicos y sociales.", t:"Modelo biopsicosocial"},
{cat:"Salud pública", d:"Enfoque que se centra en los factores que generan y mantienen la salud; usa la metáfora del \"río de la vida\".", t:"Salutogénesis"},
{cat:"Salud pública", d:"Modelo que considera al individuo un sujeto activo que participa en las decisiones y expresa creencias, necesidades y expectativas.", t:"Modelo centrado en el paciente"},
{cat:"Salud pública", d:"Circunstancias en las que las personas nacen, crecen, viven, trabajan y envejecen, que condicionan su salud (DSS).", t:"Determinantes sociales de la salud"},
{cat:"Salud pública", d:"Diferencias injustas y evitables en el estado de salud entre distintos grupos sociales.", t:"Inequidad sanitaria"},
{cat:"Salud pública", d:"Enfoque que propone incorporar la perspectiva sanitaria en todas las decisiones gubernamentales (transporte, vivienda, educación, urbanismo).", t:"Salud en Todas las Políticas (STP)"},
{cat:"Salud pública", d:"Modelo multidisciplinario que estudia cómo las experiencias individuales, junto con el contexto histórico, social y económico, influyen en la salud a lo largo del tiempo.", t:"Enfoque de curso de vida"},
{cat:"Salud pública", d:"Concepto del curso de vida: los distintos caminos que recorren las personas en áreas como el trabajo, la educación o la salud.", t:"Trayectorias"},
{cat:"Salud pública", d:"Concepto del curso de vida: momentos de cambio con nuevos roles sociales o modificaciones fisiológicas (adolescencia, maternidad, jubilación).", t:"Transiciones"},
{cat:"Salud pública", d:"Etapas de la vida en las que ciertas exposiciones tienen efectos especialmente importantes y duraderos; un ejemplo es el período prenatal.", t:"Períodos críticos y sensibles"},
{cat:"Salud pública", d:"Conjunto de capacidades físicas y mentales de una persona.", t:"Capacidad intrínseca"},
{cat:"Salud pública", d:"Resultado de la interacción entre la capacidad intrínseca y el entorno en que vive el individuo.", t:"Habilidad funcional"},
{cat:"Salud pública", d:"Expresión colectiva de la salud de los individuos de una comunidad, determinada por factores sociales, culturales y ambientales.", t:"Salud comunitaria"},
{cat:"Salud pública", d:"Recursos, capacidades o fortalezas (personas, asociaciones, instituciones, redes) que favorecen el bienestar y reducen desigualdades; participan activamente en generar salud.", t:"Activos para la salud"},
{cat:"Salud pública", d:"Proceso participativo para reconocer las fortalezas de la comunidad, con grupo promotor, análisis de situación y técnicas como los \"Paseos de Jane\" o el método \"Photovoice\".", t:"Mapeo de activos"},
{cat:"Salud pública", d:"Práctica en la que los profesionales sugieren actividades o recursos comunitarios (grupos de caminata, talleres culturales) para mejorar el bienestar.", t:"Recomendación comunitaria (prescripción social)"},
{cat:"Salud pública", d:"Herramienta que permite conocer a la persona y su familia en su contexto cotidiano real, e identificar factores como humedad en la vivienda o barreras económicas.", t:"Entrevista domiciliaria"},
{cat:"Salud pública", d:"Integración de los sistemas de salud entre los diferentes niveles de atención.", t:"Integración vertical"},
{cat:"Salud pública", d:"Integración de los sistemas de salud mediante el trabajo intersectorial.", t:"Integración horizontal"},
{cat:"Salud pública", d:"Integración de los sistemas de salud que acompaña a las personas a lo largo del tiempo.", t:"Integración longitudinal"},
{cat:"Salud pública", d:"Integración de los sistemas de salud que considera a la familia y su contexto como unidad de atención.", t:"Integración intergeneracional"},

// ===== Bioética y derechos =====
{cat:"Bioética y derechos", d:"Ley argentina de 2009 que establece los derechos del paciente en su relación con los profesionales e instituciones de salud; modificada por la Ley 26.742.", t:"Ley 26.529"},
{cat:"Bioética y derechos", d:"Ley argentina conocida como Ley de Muerte Digna: reconoce al paciente con enfermedad irreversible, incurable o terminal el derecho a rechazar procedimientos, incluidas medidas de soporte vital desproporcionadas.", t:"Ley 26.742"},
{cat:"Bioética y derechos", d:"Ley argentina que reconoce y regula el acceso a los cuidados paliativos.", t:"Ley 27.678"},
{cat:"Bioética y derechos", d:"Derecho del paciente a recibir información clara, completa y comprensible sobre diagnóstico, pronóstico, tratamientos, riesgos y alternativas; también puede renunciar a ella y delegarla en un tercero.", t:"Derecho a la información sanitaria"},
{cat:"Bioética y derechos", d:"Acto libre, voluntario y consciente por el cual el paciente acepta o rechaza un procedimiento tras ser informado; puede ser verbal o escrito y es revocable. No es solo firmar un formulario.", t:"Consentimiento informado"},
{cat:"Bioética y derechos", d:"Obligación de mantener en reserva toda la información del paciente, incluso después de su muerte; solo se rompe con autorización u orden judicial.", t:"Confidencialidad"},
{cat:"Bioética y derechos", d:"Documento por el cual una persona capaz y mayor de edad deja escritas sus decisiones sobre tratamientos futuros; deben respetarse salvo objeción de conciencia (derivando al paciente).", t:"Directivas anticipadas"},
{cat:"Bioética y derechos", d:"Situación en la que puede actuarse sin consentimiento: emergencia vital con el paciente sin poder expresar su voluntad y sin representante disponible.", t:"Excepción al consentimiento informado"},
{cat:"Bioética y derechos", d:"Acción intencional destinada a provocar la muerte mediante una sustancia letal; no está legalizada en Argentina.", t:"Eutanasia"},
{cat:"Bioética y derechos", d:"Retirar o no iniciar una intervención que el paciente rechaza, permitiendo que la enfermedad siga su curso natural; se diferencia de la eutanasia.", t:"Limitación o rechazo de tratamientos"},
{cat:"Bioética y derechos", d:"Atención cuyo objetivo es aliviar el dolor y otros síntomas y acompañar al paciente y su entorno, sin acelerar ni retrasar deliberadamente la muerte.", t:"Cuidados paliativos"},
{cat:"Bioética y derechos", d:"Caso de Estados Unidos que discutió la necesidad de evidencia suficiente sobre la voluntad previa de una persona incapaz.", t:"Caso Nancy Cruzan"},
{cat:"Bioética y derechos", d:"Caso argentino relacionado con el respeto por la decisión de un paciente competente de rechazar un tratamiento.", t:"Caso Parodi"},
{cat:"Bioética y derechos", d:"Rama de la ética aplicada que reflexiona sobre los problemas de la vida, la salud y las ciencias biomédicas; término acuñado por Van Rensselaer Potter en 1971.", t:"Bioética"},
{cat:"Bioética y derechos", d:"Modelo de cuatro principios de Beauchamp y Childress: autonomía, beneficencia, no maleficencia y justicia.", t:"Principialismo"},
{cat:"Bioética y derechos", d:"Principio bioético que reconoce al paciente como persona capaz de decidir sobre su cuerpo y su salud, incluso cuando su decisión no coincide con la del médico.", t:"Autonomía"},
{cat:"Bioética y derechos", d:"Principio bioético que obliga al profesional a actuar buscando el beneficio y bienestar del paciente.", t:"Beneficencia"},
{cat:"Bioética y derechos", d:"Principio bioético de evitar causar daño (\"primero, no hacer daño\"); antes de intervenir se evalúan riesgos y beneficios.", t:"No maleficencia"},
{cat:"Bioética y derechos", d:"Principio bioético que exige trato equitativo y digno y una distribución justa de los recursos sanitarios, sin discriminación.", t:"Justicia"},
{cat:"Bioética y derechos", d:"Informe sobre investigación que identifica tres principios: respeto por las personas, beneficencia y justicia.", t:"Informe Belmont"},
{cat:"Bioética y derechos", d:"Código surgido en 1947 como respuesta a los experimentos nazis; su principio fundamental es que el consentimiento voluntario del participante es esencial.", t:"Código de Núremberg"},
{cat:"Bioética y derechos", d:"Declaración de la Asociación Médica Mundial que establece principios éticos para la investigación en seres humanos: el bienestar de los participantes prevalece sobre los intereses de la ciencia y la sociedad.", t:"Declaración de Helsinki"},
{cat:"Bioética y derechos", d:"Requisitos éticos de una investigación: valor científico, riesgo-beneficio favorable, selección justa, consentimiento informado, evaluación independiente y protección de los participantes.", t:"Requisitos éticos de la investigación clínica"},
{cat:"Bioética y derechos", d:"Organismo que debe evaluar un proyecto de investigación de manera independiente.", t:"Comité de Ética en Investigación"},
{cat:"Bioética y derechos", d:"Diferencia básica: la práctica clínica busca el beneficio del paciente individual; la investigación busca generar conocimiento generalizable.", t:"Práctica clínica vs. investigación"},
{cat:"Bioética y derechos", d:"Error del participante que cree que el objetivo principal del estudio es su beneficio personal, cuando en realidad es generar conocimiento.", t:"Equívoco terapéutico"},
{cat:"Bioética y derechos", d:"Situación en la que un interés secundario (económico, prestigio, institucional) puede influir indebidamente en el juicio del investigador.", t:"Conflicto de interés"},
{cat:"Bioética y derechos", d:"Tendencia a publicar principalmente resultados positivos o favorables y dejar de lado los negativos.", t:"Sesgo de publicación"},
{cat:"Bioética y derechos", d:"Estudio de EE.UU. sobre la evolución natural de la sífilis en hombres afroamericanos, sin informarles adecuadamente y negándoles penicilina; vulneró autonomía, no maleficencia, beneficencia y justicia.", t:"Estudio de Tuskegee"}
];
