// TERMINOLOGIA: tarjetas de terminología médica. Reemplazá este archivo con el código generado.
// Formato: {cat:"Categoría", d:"Descripción, signos o síntomas", t:"Término"}
const TERMINOLOGIA = [
// ===== Introducción =====
{cat:"Introducción", d:"Experiencias subjetivas del paciente: lo que siente y puede describir con sus propias palabras. Solo pueden conocerse a través del interrogatorio clínico (ej.: dolor, náuseas, prurito).", t:"Síntomas"},
{cat:"Introducción", d:"Manifestaciones objetivas que el profesional identifica mediante la observación, el examen físico o estudios complementarios (ej.: fiebre medida con termómetro, edemas, soplos).", t:"Signos"},
{cat:"Introducción", d:"Recurso que se usa cuando no se encuentra el término médico adecuado: anotar textualmente lo que dice el paciente entre comillas, para preservar su experiencia subjetiva y analizarla después.", t:"Registro literal con comillas"},
{cat:"Introducción", d:"Término médico que corresponde a la expresión del paciente \"me duele la panza\".", t:"Dolor abdominal"},
{cat:"Introducción", d:"Expresión del paciente \"estoy mareado\": puede tener múltiples interpretaciones clínicas, por lo que hay que profundizar el interrogatorio antes de asignar un término definitivo.", t:"Mareo inespecífico, vértigo, lipotimia o presíncope"},
{cat:"Introducción", d:"Término médico que corresponde a la expresión del paciente \"me pica todo el cuerpo\".", t:"Prurito generalizado"},

// ===== Piel y faneras =====
{cat:"Piel y faneras", d:"Lesión elemental primaria: cambio de color, plana, no palpable, menor de 10 mm.", t:"Mácula"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: sólida y sobreelevada, menor de 10 mm.", t:"Pápula"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: superficie plana elevada, mayor de 10 mm.", t:"Placa"},
{cat:"Piel y faneras", d:"Lesión sólida, palpable, que puede ser profunda (5–10 mm o más).", t:"Nódulo"},
{cat:"Piel y faneras", d:"Lesión sólida de gran tamaño, mayor de 20 mm.", t:"Tumor"}, // REVISAR: el resumen no aclara el límite con el nódulo (5–10 mm o más)
{cat:"Piel y faneras", d:"Lesión elemental primaria con contenido líquido, menor de 10 mm.", t:"Vesícula"},
{cat:"Piel y faneras", d:"Lesión con contenido líquido de tamaño mayor a 10 mm (vesícula mayor).", t:"Ampolla (bulla)"},
{cat:"Piel y faneras", d:"Lesión elemental primaria que contiene pus.", t:"Pústula"},
{cat:"Piel y faneras", d:"Edema transitorio en la dermis (roncha).", t:"Habón"},
{cat:"Piel y faneras", d:"Lesión vascular: hemorragias puntiformes.", t:"Petequias"},
{cat:"Piel y faneras", d:"Lesión vascular: extravasación de sangre en la piel o el tejido subcutáneo.", t:"Equimosis"},
{cat:"Piel y faneras", d:"Colección de sangre en los tejidos.", t:"Hematoma"},
{cat:"Piel y faneras", d:"Dilataciones vasculares permanentes.", t:"Telangiectasias"},
{cat:"Piel y faneras", d:"Lesión secundaria: pérdida superficial de la epidermis.", t:"Erosión"},
{cat:"Piel y faneras", d:"Lesión secundaria: pérdida profunda que alcanza la dermis.", t:"Úlcera"},
{cat:"Piel y faneras", d:"Lesión secundaria producida por el rascado.", t:"Escoriación"},
{cat:"Piel y faneras", d:"Engrosamiento de la piel producido por rascado crónico.", t:"Liquenificación"},
{cat:"Piel y faneras", d:"Adelgazamiento cutáneo.", t:"Atrofia"},
{cat:"Piel y faneras", d:"Reparación fibrosa de la piel; puede ser normal, patológica o queloide.", t:"Cicatriz"},
{cat:"Piel y faneras", d:"Alteración del color de la piel por vasoconstricción o anemia.", t:"Palidez"},
{cat:"Piel y faneras", d:"Color azulado de la piel por hipoxia.", t:"Cianosis"},
{cat:"Piel y faneras", d:"Enrojecimiento de la piel por vasodilatación.", t:"Eritema"},
{cat:"Piel y faneras", d:"Coloración amarillenta de la piel y las mucosas por aumento de bilirrubina.", t:"Ictericia"},
{cat:"Piel y faneras", d:"Despigmentación de la piel.", t:"Vitiligo"},
{cat:"Piel y faneras", d:"Hiperpigmentación facial.", t:"Melasma"},
{cat:"Piel y faneras", d:"Alteración de la sudoración por obstrucción de los conductos sudoríparos.", t:"Miliaria"},
{cat:"Piel y faneras", d:"Exceso de sudor.", t:"Hiperhidrosis"},
{cat:"Piel y faneras", d:"Mal olor corporal causado por bacterias.", t:"Bromhidrosis"},
{cat:"Piel y faneras", d:"Crecimiento de vello con patrón masculino en mujeres.", t:"Hirsutismo"},
{cat:"Piel y faneras", d:"Exceso de vello de causa no hormonal.", t:"Hipertricosis"},
{cat:"Piel y faneras", d:"Pérdida parcial del pelo.", t:"Alopecia"},
{cat:"Piel y faneras", d:"Pérdida total del pelo.", t:"Calvicie"},
{cat:"Piel y faneras", d:"Encanecimiento del pelo.", t:"Canicie"},
{cat:"Piel y faneras", d:"Alteración de las uñas: manchas blancas.", t:"Leuconiquia"},
{cat:"Piel y faneras", d:"Infección de las uñas.", t:"Onixis"},
{cat:"Piel y faneras", d:"Uñas convexas.", t:"Uñas en vidrio de reloj"},
{cat:"Piel y faneras", d:"Uñas cóncavas.", t:"Coiloniquia"},
{cat:"Piel y faneras", d:"Ausencia de uñas.", t:"Anoniquia"},
{cat:"Piel y faneras", d:"Hipertrofia y curvatura de las uñas.", t:"Onicogrifosis"},
{cat:"Piel y faneras", d:"Surcos transversales en las uñas.", t:"Oniquixia"},
{cat:"Piel y faneras", d:"Hábito de morderse las uñas.", t:"Onicofagia"},

// ===== Cabeza y cuello =====
{cat:"Cabeza y cuello", d:"Conjunto de rasgos faciales (color de piel, arrugas, expresión) que orienta hacia diagnósticos específicos.", t:"Facies"},
{cat:"Cabeza y cuello", d:"Alteración palpebral: caída del párpado superior.", t:"Ptosis palpebral"},
{cat:"Cabeza y cuello", d:"Aparente caída del párpado debida a engrosamiento del mismo.", t:"Seudoptosis"},
{cat:"Cabeza y cuello", d:"Alteración palpebral: inversión del párpado.", t:"Entropión"},
{cat:"Cabeza y cuello", d:"Alteración palpebral: eversión del párpado.", t:"Ectropión"},
{cat:"Cabeza y cuello", d:"Infección estafilocócica aguda de las glándulas del párpado.", t:"Orzuelo"},
{cat:"Cabeza y cuello", d:"Dolor de oído.", t:"Otalgia"},
{cat:"Cabeza y cuello", d:"Dolor al deglutir (al tragar).", t:"Odinofagia / Deglutalgia"},
{cat:"Cabeza y cuello", d:"Dificultad para abrir la boca por contractura del músculo masetero; puede acompañar al dolor parotídeo.", t:"Trismo"},
{cat:"Cabeza y cuello", d:"Desviación lateral viciosa del cuello.", t:"Tortícolis"},
{cat:"Cabeza y cuello", d:"Eliminación de líquido por la nariz.", t:"Rinorrea"},
{cat:"Cabeza y cuello", d:"Eliminación de sangre por la nariz.", t:"Epistaxis"},
{cat:"Cabeza y cuello", d:"Eliminación de líquido cefalorraquídeo por la nariz.", t:"Craneolicuorraquia"},
{cat:"Cabeza y cuello", d:"Eliminación de líquido por el oído.", t:"Otorrea"},
{cat:"Cabeza y cuello", d:"Eliminación de sangre por el oído; es crítica en traumatismos de cráneo.", t:"Otorragia"},
{cat:"Cabeza y cuello", d:"Alteración de la calidad o el tono de la voz (ronca o bitonal), por ejemplo por parálisis nerviosa.", t:"Disfonía"},
{cat:"Cabeza y cuello", d:"Pérdida total de la voz.", t:"Afonía"},
{cat:"Cabeza y cuello", d:"Tono de voz más alto de lo normal.", t:"Falsete"},
{cat:"Cabeza y cuello", d:"Inflamación de los labios.", t:"Queilitis"},
{cat:"Cabeza y cuello", d:"Mal aliento.", t:"Halitosis"},
{cat:"Cabeza y cuello", d:"Aumento de la secreción salival.", t:"Sialorrea"},
{cat:"Cabeza y cuello", d:"Disminución o ausencia de saliva; sequedad de la boca.", t:"Xerostomía"},
{cat:"Cabeza y cuello", d:"Lengua cubierta por una placa blanquecina o amarillenta.", t:"Lengua saburral"},
{cat:"Cabeza y cuello", d:"Inflamación global de la lengua.", t:"Glositis"},
{cat:"Cabeza y cuello", d:"Dolor o ardor en la lengua.", t:"Glosodinia / Glosalgia"},
{cat:"Cabeza y cuello", d:"Pigmentación oscura de la lengua.", t:"Melanoglosia"},
{cat:"Cabeza y cuello", d:"Lengua con áreas rojas despapiladas que cambian de lugar, dándole aspecto de mapa.", t:"Lengua geográfica"},
{cat:"Cabeza y cuello", d:"Lengua con surcos o grietas profundas.", t:"Lengua escrotal (fisurada)"},

// ===== Respiratorio =====
{cat:"Respiratorio", d:"Expulsión brusca de aire para limpiar el árbol bronquial; puede ser seca o húmeda (productiva si hay expulsión).", t:"Tos"},
{cat:"Respiratorio", d:"Variedad de tos con accesos paroxísticos.", t:"Tos quintosa"},
{cat:"Respiratorio", d:"Variedad de tos que provoca vómitos.", t:"Tos emetizante"},
{cat:"Respiratorio", d:"Variedad de tos asociada a parálisis de una cuerda vocal.", t:"Tos bitonal"},
{cat:"Respiratorio", d:"Variedad de tos característica de la laringitis.", t:"Tos perruna"},
{cat:"Respiratorio", d:"Expulsión de contenido bronquial; puede ser serosa, mucosa (\"clara de huevo\"), purulenta o con sangre.", t:"Expectoración"},
{cat:"Respiratorio", d:"Sangre del árbol respiratorio expulsada con la tos; es roja rutilante y tiene burbujas de aire.", t:"Hemoptisis"},
{cat:"Respiratorio", d:"Expulsión brusca y masiva de una colección líquida (ej.: absceso de pulmón).", t:"Vómica"},
{cat:"Respiratorio", d:"Sensación subjetiva de falta de aire.", t:"Disnea"},
{cat:"Respiratorio", d:"Disnea que aparece solo ante grandes esfuerzos.", t:"Disnea clase funcional I"},
{cat:"Respiratorio", d:"Disnea que aparece ante los esfuerzos habituales.", t:"Disnea clase funcional II"},
{cat:"Respiratorio", d:"Disnea que aparece ante esfuerzos mínimos.", t:"Disnea clase funcional III"},
{cat:"Respiratorio", d:"Disnea que aparece en reposo.", t:"Disnea clase funcional IV"},
{cat:"Respiratorio", d:"Falta de aire que obliga al paciente a permanecer sentado.", t:"Ortopnea"},
{cat:"Respiratorio", d:"Falta de aire que aparece en decúbito lateral.", t:"Trepopnea"},
{cat:"Respiratorio", d:"Falta de aire que aparece al estar sentado.", t:"Platipnea"},
{cat:"Respiratorio", d:"Posición adoptada por el paciente con derrame pericárdico.", t:"Posición de plegaria mahometana"},
{cat:"Respiratorio", d:"Frecuencia respiratoria normal, de 14 a 20 respiraciones por minuto.", t:"Eupnea"},
{cat:"Respiratorio", d:"Frecuencia respiratoria aumentada, mayor de 20 por minuto.", t:"Taquipnea"},
{cat:"Respiratorio", d:"Disminución de la frecuencia respiratoria.", t:"Bradipnea"},
{cat:"Respiratorio", d:"Suspensión de la respiración.", t:"Apnea"},
{cat:"Respiratorio", d:"Dolor torácico punzante, localizado en la base del tórax, que aumenta con la inspiración profunda y la tos.", t:"Dolor pleurítico"},

// ===== Cardiovascular =====
{cat:"Cardiovascular", d:"Dolor retroesternal opresivo, irradiado a cuello, mandíbula o brazo izquierdo, frecuentemente con angustia o sensación de muerte. Si dura más de 20–30 minutos se sospecha infarto de miocardio.", t:"Angor (angina de pecho)"},
{cat:"Cardiovascular", d:"Percepción molesta de los latidos cardíacos; incluye aumento o disminución de la frecuencia y arritmias.", t:"Palpitaciones"},
{cat:"Cardiovascular", d:"Aumento de la frecuencia cardíaca (según el resumen, mayor de 80 lpm).", t:"Taquicardia"}, // REVISAR: el resumen indica >80 lpm; habitualmente se define como >100 lpm
{cat:"Cardiovascular", d:"Disminución de la frecuencia cardíaca, menor de 60 lpm.", t:"Bradicardia"},
{cat:"Cardiovascular", d:"Pérdida de conciencia precedida por un período premonitorio (náuseas, sudor, visión borrosa).", t:"Lipotimia"},
{cat:"Cardiovascular", d:"Pérdida brusca de la conciencia y del tono postural, sin aviso previo.", t:"Síncope"},
{cat:"Cardiovascular", d:"Acumulación de líquido; el de origen cardíaco suele ser simétrico, en piernas y aumenta hacia la noche.", t:"Edema cardíaco"},
{cat:"Cardiovascular", d:"Coloración azulada generalizada por aumento de hemoglobina reducida, de causa pulmonar o cardíaca congénita.", t:"Cianosis central"},
{cat:"Cardiovascular", d:"Coloración azulada por vasoconstricción (ej.: frío) que desaparece al frotar la piel.", t:"Cianosis periférica"},

// ===== Digestivo =====
{cat:"Digestivo", d:"Mnemotecnia para el estudio sistemático del dolor abdominal: aparición, localización, irradiación, carácter, intensidad, acompañantes/atenuantes/agravantes.", t:"ALICIA"},
{cat:"Digestivo", d:"Dolor abdominal de inicio de un segundo a otro; sugiere perforación o rotura.", t:"Aparición brusca"},
{cat:"Digestivo", d:"Dolor abdominal que empieza de a poco y aumenta continuamente con las horas; típico de inflamación o infección como la apendicitis.", t:"Aparición gradual"},
{cat:"Digestivo", d:"Dolor abdominal que va y viene en oleadas de intensidad.", t:"Aparición paroxística (cólico)"},
{cat:"Digestivo", d:"Dolor abdominal de inicio leve, vago e impreciso; el paciente no sabe exactamente cuándo empezó (común en procesos crónicos).", t:"Aparición insidiosa"},
{cat:"Digestivo", d:"Término que el paciente suele usar para referirse a la intensidad del dolor y no a su temporalidad.", t:"Agudo (uso del paciente)"},
{cat:"Digestivo", d:"Dolor localizado en la región central superior del abdomen.", t:"Epigastralgia"},
{cat:"Digestivo", d:"Dolor localizado en la región central inferior del abdomen.", t:"Hipogastralgia"},
{cat:"Digestivo", d:"Propagación del dolor desde su origen (ej.: hacia el dorso, región lumbar, tórax, ingles o en hemicinturón).", t:"Irradiación"},
{cat:"Digestivo", d:"Posición que adopta el paciente para aliviar el dolor abdominal: decúbito dorsal con los miembros flexionados para relajar la pared abdominal.", t:"Posición antálgica"},
{cat:"Digestivo", d:"Dificultad para tragar (a sólidos, líquidos o ambos).", t:"Disfagia"},
{cat:"Digestivo", d:"Sensación de ardor o quemazón retroesternal ascendente.", t:"Pirosis"},
{cat:"Digestivo", d:"Retorno pasivo del contenido alimentario a la boca, sin esfuerzo ni náuseas.", t:"Regurgitación"},
{cat:"Digestivo", d:"Dolor en el trayecto retroesternal.", t:"Esofagodinia"},
{cat:"Digestivo", d:"Vómito verde negruzco, con olor a materia fecal; típico de obstrucción intestinal avanzada.", t:"Vómito fecaloide"},
{cat:"Digestivo", d:"Vómito que aparece horas después de comer.", t:"Vómito tardío o de retención"},
{cat:"Digestivo", d:"Vómito que no se puede detener.", t:"Vómito incoercible"},
{cat:"Digestivo", d:"Vómito repentino, sin náuseas previas; sugiere hipertensión endocraneana.", t:"Vómito en chorro (central)"},
{cat:"Digestivo", d:"Vómito de sangre franca o con aspecto de \"borra de café\" (sangre digerida).", t:"Hematemesis"},
{cat:"Digestivo", d:"Ardor epigástrico.", t:"Acidismo"},
{cat:"Digestivo", d:"Sensación de estar demasiado lleno o \"satisfecho\" tras ingerir poca cantidad de alimento.", t:"Plenitud epigástrica posprandial"},
{cat:"Digestivo", d:"Aumento de la frecuencia (más de 3 deposiciones en 24 horas), la fluidez o el volumen de las heces.", t:"Diarrea"},
{cat:"Digestivo", d:"Diarrea de menos de 14 a 21 días de duración.", t:"Diarrea aguda"},
{cat:"Digestivo", d:"Diarrea de más de 21 a 30 días de duración.", t:"Diarrea crónica"},
{cat:"Digestivo", d:"Heces con alto contenido de grasa: brillantes, flotan, pastosas y malolientes; indican mala absorción.", t:"Esteatorrea"},
{cat:"Digestivo", d:"Disminución en la frecuencia de las deposiciones, con heces duras.", t:"Estreñimiento / Constipación"},
{cat:"Digestivo", d:"Deseo persistente y doloroso de defecar, con sensación de evacuación incompleta.", t:"Tenesmo rectal"},
{cat:"Digestivo", d:"Esfuerzo exagerado o dificultad para defecar.", t:"Disquecia"},
{cat:"Digestivo", d:"Unión duodeno-yeyunal, punto de referencia anatómico para clasificar la hemorragia digestiva en alta y baja.", t:"Ángulo de Treitz"},
{cat:"Digestivo", d:"Hemorragia digestiva por encima del ángulo de Treitz; se manifiesta con hematemesis, melena y, raramente, hematoquecia.", t:"Hemorragia digestiva alta"},
{cat:"Digestivo", d:"Hemorragia digestiva por debajo del ángulo de Treitz; se manifiesta con hematoquecia y rectorragia.", t:"Hemorragia digestiva baja"}, // REVISAR: el resumen dice "Rectoría" (probable error de tipeo por rectorragia)
{cat:"Digestivo", d:"Heces negras, brillantes, alquitranadas, pegajosas y de olor fétido (sangre digerida).", t:"Melena"},
{cat:"Digestivo", d:"Mezcla de sangre roja oscura o rutilante con las heces; puede ocurrir en hemorragia baja o, si el tránsito es muy acelerado, en la alta.", t:"Hematoquecia"},
{cat:"Digestivo", d:"Sangre roja rutilante (viva) que sale sola o envuelve al cilindro fecal sin integrarse en él; origen anal o rectal.", t:"Rectorragia"},
{cat:"Digestivo", d:"Orina de color oscuro (como té o bebida cola) que al agitarse forma espuma amarillo-verdosa.", t:"Coluria"},
{cat:"Digestivo", d:"Ausencia o disminución marcada del color normal de las heces, que se vuelven blancas o \"masilla\" por falta de pigmentos biliares.", t:"Acolia / Hipocolia"},
{cat:"Digestivo", d:"Heces intensamente coloreadas (hiperpigmentadas); muy común en crisis de anemias hemolíticas.", t:"Pleocromía fecal"}, // REVISAR: el resumen la incluye en una \"tétrada\" junto con coluria, acolia y prurito
{cat:"Digestivo", d:"Picazón generalizada, con predominio en palmas y plantas, por depósito cutáneo de sales biliares.", t:"Prurito colestásico"},
{cat:"Digestivo", d:"Líquido libre en la cavidad peritoneal; causa distensión abdominal generalizada.", t:"Ascitis"},
{cat:"Digestivo", d:"Exceso de gas intestinal; causa distensión abdominal generalizada.", t:"Meteorismo"},
{cat:"Digestivo", d:"Hinchazón del abdomen; puede ser generalizada o localizada por masas o tumores.", t:"Distensión abdominal"},
{cat:"Digestivo", d:"Ruidos hidroaéreos intestinales aumentados en intensidad y frecuencia, a veces audibles sin estetoscopio.", t:"Borborigmos"},

// ===== Nefrourinario =====
{cat:"Nefrourinario", d:"Dolor renal de intensidad variable, con exacerbaciones por espasmos ureterales, frecuentemente por cálculos.", t:"Cólico renal"},
{cat:"Nefrourinario", d:"Dolor renal por ptosis renal.", t:"Crisis de Dietl"},
{cat:"Nefrourinario", d:"Dolor renal continuo con sensación de pesadez (ej.: riñón poliquístico, tumores).", t:"Dolor renal continuo"},
{cat:"Nefrourinario", d:"Cantidad de orina eliminada en 24 horas; el valor normal es de 800 a 1500 cc.", t:"Diuresis"},
{cat:"Nefrourinario", d:"Diuresis mayor de 1500 cc en 24 horas.", t:"Poliuria"},
{cat:"Nefrourinario", d:"Diuresis menor de 800 cc en 24 horas.", t:"Oliguria"},
{cat:"Nefrourinario", d:"Diuresis menor de 400 cc en 24 horas.", t:"Oligo-anuria"},
{cat:"Nefrourinario", d:"Cese total de la secreción de orina.", t:"Anuria"},
{cat:"Nefrourinario", d:"Inversión del ritmo urinario: se orina más de noche que de día.", t:"Nicturia"},
{cat:"Nefrourinario", d:"Aumento del número de micciones; puede ser obligada por poliuria o verdadera por cistitis.", t:"Polaquiuria"},
{cat:"Nefrourinario", d:"Emisión involuntaria de orina durante el sueño; anormal después de los 4 años.", t:"Enuresis"},
{cat:"Nefrourinario", d:"Demora en eliminar el agua ingerida.", t:"Opsiuria"},
{cat:"Nefrourinario", d:"Dolor o ardor al orinar.", t:"Disuria"},
{cat:"Nefrourinario", d:"Emisión penosa de orina gota a gota.", t:"Estranguria"},
{cat:"Nefrourinario", d:"Imposibilidad de retener la orina.", t:"Incontinencia urinaria"},
{cat:"Nefrourinario", d:"Incapacidad para eliminar la orina, que puede formar un \"globo vesical\".", t:"Retención urinaria"},
{cat:"Nefrourinario", d:"Necesidad imperiosa y frecuente de orinar.", t:"Tenesmo vesical"},
{cat:"Nefrourinario", d:"Presencia de sangre en la orina (color rojo).", t:"Hematuria"},
{cat:"Nefrourinario", d:"Hematuria que aparece al inicio de la micción.", t:"Hematuria uretral"},
{cat:"Nefrourinario", d:"Hematuria que aparece al final de la micción.", t:"Hematuria vesical"},
{cat:"Nefrourinario", d:"Hematuria presente durante toda la micción.", t:"Hematuria renal"},
{cat:"Nefrourinario", d:"Presencia de pus en la orina.", t:"Piuria"},
{cat:"Nefrourinario", d:"Presencia de bacterias en la orina.", t:"Bacteriuria"},
{cat:"Nefrourinario", d:"Cuando la orina forma espuma abundante y persistente, indica la presencia de estas dos alteraciones.", t:"Proteinuria o glucosuria"},
{cat:"Nefrourinario", d:"Olor de la orina que sugiere infección (el olor fétido puede indicar cáncer de vejiga).", t:"Olor amoniacal"},
{cat:"Nefrourinario", d:"Densidad urinaria baja (la normal es 1015–1025); típica de la insuficiencia renal crónica.", t:"Hipostenuria"},

// ===== Gineco-obstétrico =====
{cat:"Gineco-obstétrico", d:"Inicio del desarrollo mamario; es el primer signo puberal femenino.", t:"Telarca"},
{cat:"Gineco-obstétrico", d:"Aparición del vello pubiano.", t:"Pubarca"},
{cat:"Gineco-obstétrico", d:"Aparición del vello axilar.", t:"Axilarca"},
{cat:"Gineco-obstétrico", d:"Primera menstruación.", t:"Menarca"},
{cat:"Gineco-obstétrico", d:"Menstruación normal: intervalos de 21 a 35 días y duración de 2 a 7 días.", t:"Ciclo menstrual normal"},
{cat:"Gineco-obstétrico", d:"Cualquier sangrado que difiere de lo normal en frecuencia, regularidad o volumen.", t:"Sangrado uterino anormal (SUA)"},
{cat:"Gineco-obstétrico", d:"Menstruación con intervalos menores de 21 días.", t:"Polimenorrea"},
{cat:"Gineco-obstétrico", d:"Menstruación con intervalos entre 35 y 90 días.", t:"Oligomenorrea"},
{cat:"Gineco-obstétrico", d:"Ausencia de menstruación durante más de 3 meses.", t:"Amenorrea"},
{cat:"Gineco-obstétrico", d:"Aumento del volumen del sangrado menstrual.", t:"Hipermenorrea"},
{cat:"Gineco-obstétrico", d:"Menstruación con duración mayor de 7 días.", t:"Menorragia"},
{cat:"Gineco-obstétrico", d:"Sangrado menstrual escaso.", t:"Hipomenorrea"},
{cat:"Gineco-obstétrico", d:"Sangrado no coincidente con el ciclo menstrual.", t:"Metrorragia"},
{cat:"Gineco-obstétrico", d:"Menstruación dolorosa.", t:"Dismenorrea"},
{cat:"Gineco-obstétrico", d:"Causas estructurales de sangrado uterino anormal: pólipo, adenomiosis, leiomioma y malignidad.", t:"PALM"},
{cat:"Gineco-obstétrico", d:"Causas no estructurales de sangrado uterino anormal: coagulopatía, trastornos ovulatorios, alteraciones endometriales, causas iatrogénicas y causas no clasificadas.", t:"COEIN"},
{cat:"Gineco-obstétrico", d:"Duración de la gestación normal: de 38 a 42 semanas.", t:"Gestación normal"},
{cat:"Gineco-obstétrico", d:"Se calcula con la fórmula: FUM + 10 días − 3 meses.", t:"Fecha probable de parto (FPP)"},
{cat:"Gineco-obstétrico", d:"Mujer que nunca ha tenido un parto.", t:"Nulípara"},
{cat:"Gineco-obstétrico", d:"Mujer que ha tenido más de un parto viable.", t:"Multípara"},
{cat:"Gineco-obstétrico", d:"Mujer embarazada.", t:"Grávida"},
{cat:"Gineco-obstétrico", d:"Patología del embarazo: hipertensión arterial y proteinuria después de la semana 20.", t:"Preeclampsia"},
{cat:"Gineco-obstétrico", d:"Aparición de convulsiones asociadas a la preeclampsia.", t:"Eclampsia"},
{cat:"Gineco-obstétrico", d:"Interrupción del embarazo antes de las 20 semanas o con un peso fetal menor de 500 g.", t:"Aborto"},
{cat:"Gineco-obstétrico", d:"Sigla que designa una de las dos modalidades de interrupción del embarazo que distingue el resumen (la otra es la legal).", t:"IVE (Interrupción Voluntaria del Embarazo)"}, // REVISAR: el resumen solo da el nombre de la sigla, sin definición
{cat:"Gineco-obstétrico", d:"Sigla que designa una de las dos modalidades de interrupción del embarazo que distingue el resumen (la otra es la voluntaria).", t:"ILE (Interrupción Legal del Embarazo)"}, // REVISAR: el resumen solo da el nombre de la sigla, sin definición
{cat:"Gineco-obstétrico", d:"Período de 60 días posteriores al parto durante el cual el organismo retorna progresivamente a su estado previo.", t:"Puerperio"},
{cat:"Gineco-obstétrico", d:"Métodos anticonceptivos como los preservativos; son los únicos que disminuyen el riesgo de ITS.", t:"Métodos de barrera"},
{cat:"Gineco-obstétrico", d:"Métodos anticonceptivos de larga duración: DIU de cobre y DIU hormonal.", t:"LARC"},
{cat:"Gineco-obstétrico", d:"Método anticonceptivo quirúrgico femenino.", t:"Ligadura tubaria"}, // REVISAR: el resumen solo lo lista como método quirúrgico, sin más definición
{cat:"Gineco-obstétrico", d:"Método anticonceptivo quirúrgico masculino.", t:"Vasectomía"}, // REVISAR: el resumen solo lo lista como método quirúrgico, sin más definición
{cat:"Gineco-obstétrico", d:"Patología caracterizada por flujo y prurito.", t:"Vaginitis"},
{cat:"Gineco-obstétrico", d:"Tumor benigno más frecuente.", t:"Mioma"},
{cat:"Gineco-obstétrico", d:"Descenso de los órganos pélvicos.", t:"Prolapso genital"},
{cat:"Gineco-obstétrico", d:"Inflamación de la mama, frecuente durante la lactancia.", t:"Mastitis"},
{cat:"Gineco-obstétrico", d:"Cirugía: extirpación del útero.", t:"Histerectomía"},
{cat:"Gineco-obstétrico", d:"Cirugía: extirpación de la mama.", t:"Mastectomía"},

// ===== Sistema nervioso =====
{cat:"Sistema nervioso", d:"Pérdida total del olfato.", t:"Anosmia"},
{cat:"Sistema nervioso", d:"Disminución parcial de la capacidad para percibir olores.", t:"Hiposmia"},
{cat:"Sistema nervioso", d:"Aumento exagerado de la sensibilidad olfatoria.", t:"Hiperosmia"},
{cat:"Sistema nervioso", d:"Percepción distorsionada de un olor.", t:"Parosmia"},
{cat:"Sistema nervioso", d:"Percepción de olores desagradables o nauseabundos.", t:"Cacosmia"},
{cat:"Sistema nervioso", d:"Percepción de olores en ausencia de un estímulo real.", t:"Alucinaciones olfatorias"},
{cat:"Sistema nervioso", d:"Pérdida total de la visión.", t:"Amaurosis"},
{cat:"Sistema nervioso", d:"Pérdida transitoria y unilateral de la visión asociada a isquemia.", t:"Amaurosis fugaz"},
{cat:"Sistema nervioso", d:"Disminución de la agudeza visual sin lesión orgánica evidente.", t:"Ambliopía"},
{cat:"Sistema nervioso", d:"Dificultad para la visión nocturna.", t:"Hemeralopía"}, // REVISAR: el resumen define hemeralopía = visión nocturna y nictalopía = visión diurna; en otras fuentes se invierten
{cat:"Sistema nervioso", d:"Dificultad para la visión diurna.", t:"Nictalopía"}, // REVISAR: ver nota de hemeralopía
{cat:"Sistema nervioso", d:"Área de pérdida parcial del campo visual.", t:"Escotoma"},
{cat:"Sistema nervioso", d:"Escotoma que corresponde al punto ciego fisiológico.", t:"Escotoma negativo"},
{cat:"Sistema nervioso", d:"Escotoma en el que el paciente percibe una mancha oscura dentro del campo visual.", t:"Escotoma positivo"},
{cat:"Sistema nervioso", d:"Pérdida de la mitad del campo visual (puede ser homónima o heterónoma).", t:"Hemianopsia"},
{cat:"Sistema nervioso", d:"Pérdida de un cuarto del campo visual.", t:"Cuadrantopsia"},
{cat:"Sistema nervioso", d:"Alteración de la percepción de los colores.", t:"Discromatopsia"},
{cat:"Sistema nervioso", d:"Ausencia de percepción de los colores.", t:"Acromatopsia"},
{cat:"Sistema nervioso", d:"Percepción alterada de los colores.", t:"Metacromatopsia"},
{cat:"Sistema nervioso", d:"Percepción de un único color.", t:"Monocromatopsia"},
{cat:"Sistema nervioso", d:"Visión doble.", t:"Diplopía"},
{cat:"Sistema nervioso", d:"Desviación ocular característica de la lesión del III par craneal.", t:"Estrabismo externo"},
{cat:"Sistema nervioso", d:"Desviación ocular convergente característica de la lesión del VI par craneal.", t:"Estrabismo interno convergente"},
{cat:"Sistema nervioso", d:"Desigualdad en el tamaño de las pupilas.", t:"Anisocoria"},
{cat:"Sistema nervioso", d:"Dilatación pupilar mayor de 4 mm.", t:"Midriasis"},
{cat:"Sistema nervioso", d:"Contracción pupilar menor de 2 mm.", t:"Miosis"},
{cat:"Sistema nervioso", d:"Alteración de la forma de la pupila.", t:"Discoria"},
{cat:"Sistema nervioso", d:"Oscilaciones rítmicas del diámetro pupilar frente a la luz.", t:"Hippus fisiológico"},
{cat:"Sistema nervioso", d:"Dolor localizado en el trayecto de un nervio.", t:"Neuralgia"},
{cat:"Sistema nervioso", d:"Parálisis facial que afecta solo la mitad inferior de la cara.", t:"Parálisis facial central"},
{cat:"Sistema nervioso", d:"Parálisis facial que compromete tanto la mitad superior como la inferior de la cara.", t:"Parálisis facial periférica"},
{cat:"Sistema nervioso", d:"Imposibilidad de cerrar completamente el ojo.", t:"Lagoftalmo"},
{cat:"Sistema nervioso", d:"Lagrimeo.", t:"Epífora"},
{cat:"Sistema nervioso", d:"Contracciones involuntarias de un lado de la cara.", t:"Hemiespasmo facial"},
{cat:"Sistema nervioso", d:"Pérdida total de la audición.", t:"Anacusia"},
{cat:"Sistema nervioso", d:"Disminución de la audición.", t:"Hipoacusia"},
{cat:"Sistema nervioso", d:"Sensibilidad exagerada a los sonidos.", t:"Hiperacusia"},
{cat:"Sistema nervioso", d:"Mejor audición en ambientes ruidosos.", t:"Paracusia"},
{cat:"Sistema nervioso", d:"Percepción de zumbidos u otros sonidos sin un estímulo externo.", t:"Acúfenos"},
{cat:"Sistema nervioso", d:"Sensación de giro del propio cuerpo o del ambiente.", t:"Vértigo"},
{cat:"Sistema nervioso", d:"Sensación inespecífica de inestabilidad.", t:"Mareo"},
{cat:"Sistema nervioso", d:"Movimiento ocular involuntario, rítmico y repetitivo.", t:"Nistagmo"},
{cat:"Sistema nervioso", d:"Pérdida del gusto.", t:"Ageusia"},
{cat:"Sistema nervioso", d:"Disminución del gusto.", t:"Hipogeusia"},
{cat:"Sistema nervioso", d:"Percepción distorsionada del gusto.", t:"Parageusia"},
{cat:"Sistema nervioso", d:"Voz de tonalidad nasal.", t:"Rinolalia"},
{cat:"Sistema nervioso", d:"Emisión simultánea de dos tonos de voz.", t:"Voz bitonal"},
{cat:"Sistema nervioso", d:"Marcha normal.", t:"Eubasia"},
{cat:"Sistema nervioso", d:"Marcha lenta con pasos cortos.", t:"Bradibasia"},
{cat:"Sistema nervioso", d:"Marcha patológica.", t:"Disbasia"},
{cat:"Sistema nervioso", d:"Aumento del tono muscular.", t:"Hipertonía"},
{cat:"Sistema nervioso", d:"Disminución del tono muscular.", t:"Hipotonía"},
{cat:"Sistema nervioso", d:"Ausencia de tono muscular.", t:"Atonía"},
{cat:"Sistema nervioso", d:"Oscilación del tono muscular.", t:"Distonía"},
{cat:"Sistema nervioso", d:"Pérdida total de la fuerza muscular.", t:"Parálisis"},
{cat:"Sistema nervioso", d:"Disminución parcial de la fuerza muscular.", t:"Paresia"},
{cat:"Sistema nervioso", d:"Clasificación de la pérdida de fuerza según su distribución en el cuerpo.", t:"Hemiplejia / Monoplejia / Paraplejia / Cuadriplejia"}, // REVISAR: el resumen solo enumera los términos, sin definir cada uno
{cat:"Sistema nervioso", d:"Movimientos involuntarios bruscos, breves y súbitos.", t:"Mioclonías"},
{cat:"Sistema nervioso", d:"Movimiento involuntario rítmico.", t:"Temblor"},
{cat:"Sistema nervioso", d:"Movimientos involuntarios amplios, rápidos y bruscos.", t:"Movimientos coreicos"},
{cat:"Sistema nervioso", d:"Movimientos involuntarios lentos y ondulantes.", t:"Movimientos atetósicos"},
{cat:"Sistema nervioso", d:"Movimientos involuntarios repetitivos.", t:"Tics"},
{cat:"Sistema nervioso", d:"Convulsiones con contracción muscular sostenida.", t:"Convulsiones tónicas"},
{cat:"Sistema nervioso", d:"Convulsiones con contracciones musculares repetidas.", t:"Convulsiones clónicas"},
{cat:"Sistema nervioso", d:"Ausencia de sensibilidad.", t:"Anestesia"},
{cat:"Sistema nervioso", d:"Disminución de la sensibilidad.", t:"Hipoestesia"},
{cat:"Sistema nervioso", d:"Aumento de la sensibilidad.", t:"Hiperestesia"},
{cat:"Sistema nervioso", d:"Sensación anormal como hormigueo o adormecimiento.", t:"Parestesias"},
{cat:"Sistema nervioso", d:"Sensibilidad a la presión.", t:"Barestesia"},
{cat:"Sistema nervioso", d:"Capacidad para reconocer el peso de un objeto.", t:"Barognosia"},
{cat:"Sistema nervioso", d:"Sensibilidad vibratoria.", t:"Palestesia"},
{cat:"Sistema nervioso", d:"Capacidad para reconocer la posición de las distintas partes del cuerpo.", t:"Batiestesia"},
{cat:"Sistema nervioso", d:"Percepción del movimiento.", t:"Cinestesia"},
{cat:"Sistema nervioso", d:"Capacidad para reconocer un objeto mediante el tacto.", t:"Esterognosia"},
{cat:"Sistema nervioso", d:"Capacidad para ejecutar actos motores aprendidos.", t:"Praxia"},
{cat:"Sistema nervioso", d:"Pérdida de la capacidad para ejecutar actos motores aprendidos.", t:"Apraxia"},
{cat:"Sistema nervioso", d:"Capacidad para reconocer estímulos sensoriales.", t:"Gnosia"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer estímulos sensoriales.", t:"Agnosia"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer partes del propio cuerpo.", t:"Agnosia corporal"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer la propia enfermedad.", t:"Anosognosia"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer el cuerpo como un todo.", t:"Autotopagnosia"},
{cat:"Sistema nervioso", d:"Ausencia de expresión facial.", t:"Amimia"},
{cat:"Sistema nervioso", d:"Alteración en el cálculo de la distancia de los movimientos.", t:"Dismetría"},
{cat:"Sistema nervioso", d:"Repetición innecesaria de gestos o conductas.", t:"Estereotipia"},
{cat:"Sistema nervioso", d:"Estado máximo de alteración de la conciencia.", t:"Coma"}
];
