const TERMINOLOGIA = [
// ===== Introducción =====
{cat:"Introducción", d:"Experiencias subjetivas del paciente, es decir, aquello que siente y puede describir con sus propias palabras. Solo pueden conocerse a través del interrogatorio clínico. Ejemplos frecuentes: dolor, disnea, mareos, náuseas y prurito.", t:"Síntomas"},
{cat:"Introducción", d:"Manifestaciones objetivas que el profesional puede identificar mediante la observación, el examen físico o estudios complementarios. Ejemplos: fiebre medida con termómetro, lesiones visibles, edemas o soplos auscultatorios.", t:"Signos"},
{cat:"Introducción", d:"Su correcta diferenciación (síntomas subjetivos vs. signos objetivos) permite ordenar la información clínica, elaborar adecuadamente la historia clínica y orientar tanto el diagnóstico como el tratamiento.", t:"Importancia de diferenciar signos y síntomas"},
{cat:"Introducción", d:"Sistema de comunicación estandarizado entre profesionales de la salud. Permite expresar información de manera clara y precisa, facilitar el trabajo interdisciplinario, garantizar la continuidad del cuidado y aumentar la seguridad del paciente. Su aprendizaje es progresivo y se desarrolla a lo largo de la formación médica.", t:"Lenguaje médico"},
{cat:"Introducción", d:"Proceso durante la anamnesis en el que el profesional traduce las expresiones cotidianas del paciente a términos médicos, logrando precisión sin perder el sentido original de lo que el paciente experimenta. Requiere no solo conocimiento, sino también capacidad de interpretación clínica.", t:"Traducción del lenguaje cotidiano al lenguaje médico"},
{cat:"Introducción", d:"Recurso correcto cuando no se identifica de inmediato el término médico adecuado (por el proceso de aprendizaje o la complejidad del relato): registrar literalmente lo que el paciente expresa, entre comillas. Preserva la experiencia subjetiva original y sirve de base para un análisis posterior, buscando luego consensuar el término apropiado sin distorsionar el significado inicial.", t:"Registro literal con comillas"},
{cat:"Introducción", d:"Término médico que corresponde a la expresión del paciente \"Me duele la panza\".", t:"Dolor abdominal"},
{cat:"Introducción", d:"Término médico que corresponde a la expresión del paciente \"Me falta el aire\".", t:"Disnea (expresión del paciente)"},
{cat:"Introducción", d:"Término médico que corresponde a la expresión del paciente \"Me arde al orinar\".", t:"Disuria (expresión del paciente)"},
{cat:"Introducción", d:"Término médico que corresponde a la expresión del paciente \"Siento el corazón acelerado\".", t:"Palpitaciones (expresión del paciente)"},
{cat:"Introducción", d:"Expresión del paciente \"Estoy mareado\": puede corresponder a mareo inespecífico, vértigo, lipotimia o presíncope. Ciertas expresiones tienen múltiples interpretaciones clínicas, por lo que hay que profundizar el interrogatorio antes de asignar un término definitivo.", t:"Mareo inespecífico, vértigo, lipotimia o presíncope"},
{cat:"Introducción", d:"Término médico que corresponde a la expresión del paciente \"Me pica todo el cuerpo\".", t:"Prurito generalizado"},
{cat:"Introducción", d:"Aprender terminología médica no es solo conocer términos: también implica escuchar activamente al paciente, interpretar correctamente su relato, comunicar la información de manera precisa y mantener un enfoque centrado en la persona. Es un proceso progresivo, basado en la práctica, la reflexión y el intercambio con otros profesionales.", t:"Integración de la terminología en la formación médica"},

// ===== Piel y faneras =====
{cat:"Piel y faneras", d:"Órgano de observación directa cuya correcta evaluación permite traducir los síntomas del paciente a un lenguaje médico preciso, evitando diagnósticos apresurados. Para describir una lesión se consideran: tipo, tamaño, forma, color, contenido, distribución y evolución.", t:"Piel"},
{cat:"Piel y faneras", d:"Lesiones iniciales, no modificadas (mácula, pápula, placa, nódulo, tumor, vesícula, ampolla, pústula, habón).", t:"Lesiones elementales primarias"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: cambio de color, plana, no palpable, menor de 10 mm.", t:"Mácula"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: sólida y sobreelevada, menor de 10 mm.", t:"Pápula"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: superficie plana elevada, mayor de 10 mm.", t:"Placa"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: sólida, palpable, que puede ser profunda; mide 5–10 mm o más.", t:"Nódulo"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: sólida, de gran tamaño, mayor de 20 mm.", t:"Tumor"}, // REVISAR: el resumen no aclara el límite con el nódulo (5–10 mm o más)
{cat:"Piel y faneras", d:"Lesión elemental primaria con contenido líquido, menor de 10 mm.", t:"Vesícula"},
{cat:"Piel y faneras", d:"Vesícula mayor: lesión con contenido líquido de más de 10 mm.", t:"Ampolla (bulla)"},
{cat:"Piel y faneras", d:"Lesión elemental primaria que contiene pus.", t:"Pústula"},
{cat:"Piel y faneras", d:"Lesión elemental primaria: edema transitorio en la dermis (roncha).", t:"Habón (roncha)"},
{cat:"Piel y faneras", d:"Lesión vascular: hemorragias puntiformes.", t:"Petequias"},
{cat:"Piel y faneras", d:"Lesión vascular: extravasación sanguínea en la piel o el tejido subcutáneo.", t:"Equimosis"},
{cat:"Piel y faneras", d:"Lesión vascular: colección de sangre en los tejidos.", t:"Hematoma"},
{cat:"Piel y faneras", d:"Lesión vascular: dilataciones vasculares permanentes.", t:"Telangiectasias"},
{cat:"Piel y faneras", d:"Lesiones que surgen por evolución o manipulación de las lesiones primarias (erosión, úlcera, escoriación, liquenificación, atrofia, cicatriz).", t:"Lesiones elementales secundarias"},
{cat:"Piel y faneras", d:"Lesión secundaria: pérdida superficial de la epidermis.", t:"Erosión"},
{cat:"Piel y faneras", d:"Lesión secundaria: pérdida profunda que alcanza la dermis.", t:"Úlcera"},
{cat:"Piel y faneras", d:"Lesión secundaria producida por el rascado.", t:"Escoriación"},
{cat:"Piel y faneras", d:"Lesión secundaria: engrosamiento de la piel por rascado crónico.", t:"Liquenificación"},
{cat:"Piel y faneras", d:"Lesión secundaria: adelgazamiento cutáneo.", t:"Atrofia"},
{cat:"Piel y faneras", d:"Lesión secundaria: reparación fibrosa de la piel; puede ser normal, patológica o queloide.", t:"Cicatriz"},
{cat:"Piel y faneras", d:"Alteración del color de la piel por vasoconstricción o anemia.", t:"Palidez"},
{cat:"Piel y faneras", d:"Color azul de la piel por hipoxia.", t:"Cianosis"},
{cat:"Piel y faneras", d:"Enrojecimiento de la piel por vasodilatación.", t:"Eritema"},
{cat:"Piel y faneras", d:"Alteración del color de la piel: coloración amarilla.", t:"Ictericia"},
{cat:"Piel y faneras", d:"Despigmentación de la piel.", t:"Vitiligo"},
{cat:"Piel y faneras", d:"Hiperpigmentación facial.", t:"Melasma"},
{cat:"Piel y faneras", d:"Alteración de la sudoración por obstrucción de los conductos sudoríparos.", t:"Miliaria"},
{cat:"Piel y faneras", d:"Exceso de sudor.", t:"Hiperhidrosis"},
{cat:"Piel y faneras", d:"Mal olor del sudor causado por bacterias.", t:"Bromhidrosis"},
{cat:"Piel y faneras", d:"Crecimiento de vello con patrón masculino en mujeres.", t:"Hirsutismo"},
{cat:"Piel y faneras", d:"Exceso de vello de causa no hormonal.", t:"Hipertricosis"},
{cat:"Piel y faneras", d:"Pérdida parcial del pelo.", t:"Alopecia"},
{cat:"Piel y faneras", d:"Pérdida total del pelo.", t:"Calvicie"},
{cat:"Piel y faneras", d:"Encanecimiento del pelo.", t:"Canicie"},
{cat:"Piel y faneras", d:"Alteración de las uñas: manchas blancas.", t:"Leuconiquia"},
{cat:"Piel y faneras", d:"Infección de las uñas.", t:"Onixis"},
{cat:"Piel y faneras", d:"Alteración de las uñas: uñas convexas.", t:"Uñas en vidrio de reloj"},
{cat:"Piel y faneras", d:"Alteración de las uñas: uñas cóncavas.", t:"Coiloniquia"},
{cat:"Piel y faneras", d:"Ausencia de uñas.", t:"Anoniquia"},
{cat:"Piel y faneras", d:"Alteración de las uñas: hipertrofia y curvatura.", t:"Onicogrifosis"},
{cat:"Piel y faneras", d:"Alteración de las uñas: surcos transversales.", t:"Oniquixia"},
{cat:"Piel y faneras", d:"Hábito de morderse las uñas.", t:"Onicofagia"},

// ===== Cabeza y cuello =====
{cat:"Cabeza y cuello", d:"Conjunto de rasgos faciales que incluyen color de piel, arrugas y expresión, orientando hacia diagnósticos específicos.", t:"Facies"},
{cat:"Cabeza y cuello", d:"Alteración palpebral: caída del párpado.", t:"Ptosis palpebral"},
{cat:"Cabeza y cuello", d:"Alteración palpebral: aparente caída del párpado por engrosamiento del mismo.", t:"Seudoptosis"},
{cat:"Cabeza y cuello", d:"Alteración palpebral: inversión del párpado.", t:"Entropión"},
{cat:"Cabeza y cuello", d:"Alteración palpebral: eversión del párpado.", t:"Ectropión"},
{cat:"Cabeza y cuello", d:"Infección estafilocócica aguda de las glándulas del párpado.", t:"Orzuelo"},
{cat:"Cabeza y cuello", d:"Dolor de oído.", t:"Otalgia"},
{cat:"Cabeza y cuello", d:"Dolor al deglutir.", t:"Odinofagia"},
{cat:"Cabeza y cuello", d:"Dificultad para abrir la boca; puede acompañar al dolor parotídeo. Se debe a contractura del músculo masetero (V par craneal).", t:"Trismo"},
{cat:"Cabeza y cuello", d:"Desviación lateral viciosa del cuello.", t:"Tortícolis"},
{cat:"Cabeza y cuello", d:"Eliminación de líquido nasal.", t:"Rinorrea"},
{cat:"Cabeza y cuello", d:"Eliminación de sangre por la nariz.", t:"Epistaxis"},
{cat:"Cabeza y cuello", d:"Eliminación de líquido cefalorraquídeo por la nariz.", t:"Craneolicuorraquia"},
{cat:"Cabeza y cuello", d:"Eliminación de líquido por el oído.", t:"Otorrea"},
{cat:"Cabeza y cuello", d:"Eliminación de sangre por el oído; es crítica en traumatismos de cráneo.", t:"Otorragia"},
{cat:"Cabeza y cuello", d:"Alteración de la fonación: voz ronca o bitonal por parálisis nerviosa (alteración de la calidad o el tono de la voz).", t:"Disfonía"},
{cat:"Cabeza y cuello", d:"Pérdida total de la voz.", t:"Afonía"},
{cat:"Cabeza y cuello", d:"Tono de voz más alto de lo normal.", t:"Falsete"},
{cat:"Cabeza y cuello", d:"Inflamación de los labios.", t:"Queilitis"},
{cat:"Cabeza y cuello", d:"Mal aliento.", t:"Halitosis"},
{cat:"Cabeza y cuello", d:"Exceso de saliva (aumento de la secreción salival).", t:"Sialorrea"},
{cat:"Cabeza y cuello", d:"Sequedad de la boca por disminución o ausencia de saliva.", t:"Xerostomía"},
{cat:"Cabeza y cuello", d:"Lengua cubierta por una capa blanca o amarilla (placa blanquecina o amarillenta).", t:"Lengua saburral"},
{cat:"Cabeza y cuello", d:"Inflamación global de la lengua.", t:"Glositis"},
{cat:"Cabeza y cuello", d:"Dolor o ardor en la lengua.", t:"Glosodinia / Glosalgia"},
{cat:"Cabeza y cuello", d:"Pigmentación oscura de la lengua.", t:"Melanoglosia"},
{cat:"Cabeza y cuello", d:"Lengua con aspecto de mapa: áreas eritematosas (rojas) despapiladas que cambian de lugar.", t:"Lengua geográfica"},
{cat:"Cabeza y cuello", d:"Lengua con surcos profundos o grietas (también llamada fisurada).", t:"Lengua escrotal (fisurada)"},

// ===== Respiratorio =====
{cat:"Respiratorio", d:"Expulsión brusca de aire para limpiar el árbol bronquial. Puede ser seca o húmeda (productiva si hay expulsión).", t:"Tos"},
{cat:"Respiratorio", d:"Variedad de tos con accesos paroxísticos.", t:"Tos quintosa"},
{cat:"Respiratorio", d:"Variedad de tos que provoca vómitos.", t:"Tos emetizante"},
{cat:"Respiratorio", d:"Variedad de tos asociada a parálisis de cuerda vocal.", t:"Tos bitonal"},
{cat:"Respiratorio", d:"Variedad de tos característica de la laringitis.", t:"Tos perruna"},
{cat:"Respiratorio", d:"Expulsión de contenido bronquial. Puede ser serosa, mucosa (\"clara de huevo\"), purulenta o hemoptoica (con sangre).", t:"Expectoración"},
{cat:"Respiratorio", d:"Sangre del árbol respiratorio expulsada con la tos. Se diferencia de la hematemesis (vómito de sangre digestiva) porque es roja rutilante y tiene burbujas de aire.", t:"Hemoptisis"},
{cat:"Respiratorio", d:"Expulsión brusca y masiva de una colección líquida (ej.: absceso de pulmón).", t:"Vómica"},
{cat:"Respiratorio", d:"Sensación subjetiva de falta de aire.", t:"Disnea"},
{cat:"Respiratorio", d:"Clase funcional de la disnea: aparece ante grandes esfuerzos.", t:"Disnea clase funcional I"},
{cat:"Respiratorio", d:"Clase funcional de la disnea: aparece ante esfuerzos habituales.", t:"Disnea clase funcional II"},
{cat:"Respiratorio", d:"Clase funcional de la disnea: aparece ante esfuerzos mínimos.", t:"Disnea clase funcional III"},
{cat:"Respiratorio", d:"Clase funcional de la disnea: aparece en reposo.", t:"Disnea clase funcional IV"},
{cat:"Respiratorio", d:"Variante posicional de la disnea: el paciente necesita estar sentado.", t:"Ortopnea"},
{cat:"Respiratorio", d:"Variante posicional de la disnea: aparece en decúbito lateral.", t:"Trepopnea"},
{cat:"Respiratorio", d:"Variante posicional de la disnea: aparece al estar sentado.", t:"Platipnea"},
{cat:"Respiratorio", d:"Posición adoptada por el paciente con derrame pericárdico.", t:"Posición de plegaria mahometana"},
{cat:"Respiratorio", d:"Frecuencia respiratoria normal: 14–20 respiraciones por minuto.", t:"Eupnea"},
{cat:"Respiratorio", d:"Frecuencia respiratoria aumentada: más de 20 respiraciones por minuto.", t:"Taquipnea"},
{cat:"Respiratorio", d:"Disminución de la frecuencia respiratoria.", t:"Bradipnea"},
{cat:"Respiratorio", d:"Suspensión de la respiración.", t:"Apnea"},
{cat:"Respiratorio", d:"Dolor torácico punzante, localizado en la base del tórax, que aumenta con la inspiración profunda y la tos.", t:"Dolor pleurítico"},
{cat:"Respiratorio", d:"Caso de referencia: mujer de 35 años con antecedentes de asma. Progresión de disnea a clase III-IV, sibilancias audibles y tos seca paroxística tras exposición a polvo (alérgeno). Se constató taquipnea (28 rpm) e hipoxemia (saturación 89%). La radiografía mostró hiperinsuflación torácica por atrapamiento aéreo.", t:"Exacerbación asmática"},

// ===== Cardiovascular =====
{cat:"Cardiovascular", d:"Dolor retroesternal opresivo, irradiado a cuello, mandíbula o brazo izquierdo, frecuentemente con angustia o sensación de muerte. Si dura más de 20–30 minutos, se sospecha infarto de miocardio.", t:"Angor (angina de pecho)"},
{cat:"Cardiovascular", d:"Percepción molesta de los latidos. Incluye taquicardia, bradicardia y arritmias.", t:"Palpitaciones"},
{cat:"Cardiovascular", d:"Aumento de la frecuencia cardíaca: más de 80 lpm según el resumen.", t:"Taquicardia"}, // REVISAR: el resumen indica >80 lpm; habitualmente se define como >100 lpm
{cat:"Cardiovascular", d:"Disminución de la frecuencia cardíaca: menos de 60 lpm.", t:"Bradicardia"},
{cat:"Cardiovascular", d:"Se diferencia del síncope porque tiene un período premonitor (náuseas, sudor, visión borrosa).", t:"Lipotimia"},
{cat:"Cardiovascular", d:"Pérdida brusca de conciencia y tono postural sin aviso previo (a diferencia de la lipotimia, que tiene período premonitor).", t:"Síncope"},
{cat:"Cardiovascular", d:"Acumulación de líquido. El de origen cardíaco suele ser simétrico, en piernas y aumenta hacia la noche.", t:"Edema (cardíaco)"},
{cat:"Cardiovascular", d:"Coloración azulada por aumento de hemoglobina reducida. La forma central (causa pulmonar o cardíaca congénita) es generalizada.", t:"Cianosis central"},
{cat:"Cardiovascular", d:"Coloración azulada por aumento de hemoglobina reducida. Se debe a vasoconstricción por frío y desaparece al frotar la piel.", t:"Cianosis periférica"},
{cat:"Cardiovascular", d:"Caso de referencia: varón de 58 años, hipertenso y fumador, con angor de intensidad 10/10, asociado a diaforesis (sudoración profusa) y disnea. Taquicardia (102 lpm) y tensión arterial elevada (165/102 mmHg). El diagnóstico se confirma por elevación de enzimas cardíacas y supradesnivel del segmento ST en el ECG.", t:"Infarto agudo de miocardio"},
{cat:"Cardiovascular", d:"Sudoración profusa (presente en el caso de infarto agudo de miocardio junto al angor y la disnea).", t:"Diaforesis"},

// ===== Digestivo =====
{cat:"Digestivo", d:"Los síntomas de este aparato son uno de los motivos de consulta más frecuentes. Está compuesto por órganos encargados de la ingestión, digestión, absorción y eliminación de los alimentos.", t:"Aparato digestivo"},
{cat:"Digestivo", d:"Sensación subjetiva desagradable que varía desde una molestia leve hasta un grado severo e incapacitante. Para su estudio sistemático se usa la mnemotecnia ALICIA.", t:"Dolor abdominal"},
{cat:"Digestivo", d:"Mnemotecnia para el estudio del dolor abdominal: Aparición, Localización, Irradiación, Carácter, Intensidad, Acompañantes/Atenuantes/Agravantes.", t:"ALICIA"},
{cat:"Digestivo", d:"Aparición del dolor abdominal: empieza de un segundo a otro; sugiere perforación o rotura.", t:"Aparición brusca"},
{cat:"Digestivo", d:"Aparición del dolor abdominal: empieza de a poco y aumenta continuamente con las horas; típico de inflamación/infección como apendicitis.", t:"Aparición gradual"},
{cat:"Digestivo", d:"Aparición del dolor abdominal (cólico): dolor que va y viene en oleadas de intensidad.", t:"Aparición paroxística (cólico)"},
{cat:"Digestivo", d:"Aparición del dolor abdominal: inicio leve, vago e impreciso; el paciente no sabe exactamente cuándo empezó (común en procesos crónicos).", t:"Aparición insidiosa"},
{cat:"Digestivo", d:"Término que el paciente suele usar para referirse a la intensidad del dolor y no a la temporalidad.", t:"\"Agudo\" (uso del paciente)"},
{cat:"Digestivo", d:"El abdomen se divide en 9 regiones por líneas medioclaviculares y transversales (reborde costal y fosas ilíacas). Incluyen hipocondrios, epigastrio, flancos o vacíos, mesogastrio (umbilical), fosas ilíacas e hipogastrio. También puede ser un dolor difuso.", t:"Localización del dolor abdominal (9 regiones)"},
{cat:"Digestivo", d:"Dolor localizado en el epigastrio.", t:"Epigastralgia"},
{cat:"Digestivo", d:"Dolor localizado en el hipogastrio.", t:"Hipogastralgia"},
{cat:"Digestivo", d:"Propagación del dolor desde su origen (ej.: hacia el dorso, región lumbar, tórax, ingles o en hemicinturón).", t:"Irradiación"},
{cat:"Digestivo", d:"Descripción del dolor: continuo, cólico (con exacerbaciones), urente (quemante), opresivo o punzante.", t:"Carácter del dolor"},
{cat:"Digestivo", d:"Grado de severidad del dolor, cuantificado generalmente en una escala del 1 al 10.", t:"Intensidad del dolor"},
{cat:"Digestivo", d:"Síntomas asociados al dolor (náuseas, fiebre, diarrea) y factores que lo modifican, como la ingesta, medicamentos o la posición antálgica.", t:"Acompañantes, atenuantes y agravantes"},
{cat:"Digestivo", d:"Posición que adopta el paciente para aliviar el dolor: frecuentemente decúbito dorsal con miembros flexionados para relajar la pared abdominal.", t:"Posición antálgica"},
{cat:"Digestivo", d:"Aumento de la secreción salival.", t:"Sialorrea (digestivo)"},
{cat:"Digestivo", d:"Disminución o ausencia de saliva (boca seca).", t:"Xerostomía (digestivo)"},
{cat:"Digestivo", d:"Mal aliento.", t:"Halitosis (digestivo)"},
{cat:"Digestivo", d:"Dolor o ardor en la lengua.", t:"Glosalgia"},
{cat:"Digestivo", d:"Lengua cubierta por una placa blanquecina o amarillenta.", t:"Lengua saburral (digestivo)"},
{cat:"Digestivo", d:"Inflamación global de la lengua.", t:"Glositis (digestivo)"},
{cat:"Digestivo", d:"Lengua con áreas eritematosas (rojas) despapiladas que cambian de lugar.", t:"Lengua geográfica (digestivo)"},
{cat:"Digestivo", d:"Lengua que presenta surcos o grietas profundas.", t:"Lengua escrotal (digestivo)"},
{cat:"Digestivo", d:"Dificultad para tragar; puede ser a sólidos, líquidos o ambos.", t:"Disfagia"},
{cat:"Digestivo", d:"Dolor al tragar.", t:"Deglutalgia / Odinofagia"},
{cat:"Digestivo", d:"Sensación de ardor o quemazón retroesternal ascendente.", t:"Pirosis"},
{cat:"Digestivo", d:"Retorno pasivo del contenido alimentario a la boca, sin esfuerzo ni náuseas.", t:"Regurgitación"},
{cat:"Digestivo", d:"Dolor en el trayecto retroesternal.", t:"Esofagodinia"},
{cat:"Digestivo", d:"Expulsión violenta del contenido gástrico. Puede ser alimentario, biliar o fecaloide.", t:"Náuseas y vómitos"},
{cat:"Digestivo", d:"Vómito verde negruzco, con olor a materia fecal; típico de obstrucción intestinal avanzada.", t:"Vómito fecaloide"},
{cat:"Digestivo", d:"Tipos de vómito según su aparición: matutino, posprandial, tardío o de retención (horas después de comer), postural o incoercible (que no se puede detener).", t:"Tipos de vómito según su aparición"},
{cat:"Digestivo", d:"Vómito que aparece horas después de comer.", t:"Vómito tardío o de retención"},
{cat:"Digestivo", d:"Vómito que no se puede detener.", t:"Vómito incoercible"},
{cat:"Digestivo", d:"Vómito que se produce de forma repentina, sin náuseas previas. Sugiere hipertensión endocraneana.", t:"Vómito en chorro (o central)"},
{cat:"Digestivo", d:"Vómito de sangre franca o con aspecto de \"borra de café\" (sangre digerida).", t:"Hematemesis"},
{cat:"Digestivo", d:"Ardor epigástrico.", t:"Acidismo"},
{cat:"Digestivo", d:"Sensación de estar demasiado lleno o \"satisfecho\" tras ingerir poca cantidad de alimento.", t:"Plenitud epigástrica posprandial"},
{cat:"Digestivo", d:"Aumento de la frecuencia (más de 3 deposiciones en 24 horas), fluidez o volumen de las heces.", t:"Diarrea"},
{cat:"Digestivo", d:"Diarrea con menos de 14 a 21 días de duración.", t:"Diarrea aguda"},
{cat:"Digestivo", d:"Diarrea con más de 21 a 30 días de duración.", t:"Diarrea crónica"},
{cat:"Digestivo", d:"Heces con alto contenido de grasa; se ven brillantes, flotan y son pastosas y malolientes (indica mala absorción).", t:"Esteatorrea"},
{cat:"Digestivo", d:"Disminución en la frecuencia de las deposiciones, acompañadas de heces duras.", t:"Estreñimiento / Constipación"},
{cat:"Digestivo", d:"Deseo persistente y doloroso de defecar, con la sensación de una evacuación incompleta.", t:"Tenesmo rectal"},
{cat:"Digestivo", d:"Esfuerzo exagerado o dificultad al defecar.", t:"Disquecia"},
{cat:"Digestivo", d:"Unión duodeno-yeyunal; punto de referencia anatómico para dividir clínicamente la hemorragia digestiva en alta y baja.", t:"Ángulo de Treitz"},
{cat:"Digestivo", d:"Hemorragia digestiva por encima del ángulo de Treitz. Manifestaciones: hematemesis, melena y hematoquecia (rara).", t:"Hemorragia digestiva alta"},
{cat:"Digestivo", d:"Hemorragia digestiva por debajo del ángulo de Treitz. Manifestaciones: hematoquecia y rectorragia.", t:"Hemorragia digestiva baja"}, // REVISAR: el resumen escribe "Rectoría" (probable error de tipeo de rectorragia)
{cat:"Digestivo", d:"Heces negras, brillantes, alquitranadas, pegajosas y de olor fétido (sangre digerida).", t:"Melena"},
{cat:"Digestivo", d:"Mezcla de sangre con heces. En la hemorragia alta ocurre si el tránsito está muy acelerado; en la baja es sangre roja oscura o rutilante mezclada con las heces.", t:"Hematoquecia"},
{cat:"Digestivo", d:"Sangre roja rutilante (viva) que sale sola o envuelve al cilindro fecal sin integrarse en él (origen anal/rectal).", t:"Rectorragia"},
{cat:"Digestivo", d:"Los problemas en hígado, vías biliares y páncreas suelen manifestarse con dolor en el hipocondrio derecho (que puede irradiarse \"en el cinturón\" hacia la espalda si se compromete el páncreas) e ictericia (coloración amarillenta de piel y mucosas por aumento de bilirrubina).", t:"Hígado, vías biliares y páncreas"},
{cat:"Digestivo", d:"Orina de color oscuro (como té o bebida cola) que al agitarse forma una espuma de color amarillo-verdoso.", t:"Coluria"},
{cat:"Digestivo", d:"Ausencia o disminución marcada del color normal de las heces, que se vuelven blancas o \"masilla\" por falta de pigmentos biliares.", t:"Acolia / Hipocolia"},
{cat:"Digestivo", d:"Heces intensamente coloreadas (hiperpigmentadas), muy común en crisis de anemias hemolíticas.", t:"Pleocromía fecal"}, // REVISAR: el resumen la incluye en una "tétrada" junto con coluria, acolia y prurito
{cat:"Digestivo", d:"Picazón generalizada (con predominio en palmas y plantas) debido al depósito cutáneo de sales biliares.", t:"Prurito colestásico"},
{cat:"Digestivo", d:"Hinchazón del abdomen. Puede ser generalizada (ascitis o meteorismo) o localizada por la presencia de masas o tumores.", t:"Distensión abdominal"},
{cat:"Digestivo", d:"Líquido libre en la cavidad peritoneal; causa de distensión abdominal generalizada.", t:"Ascitis"},
{cat:"Digestivo", d:"Exceso de gas; causa de distensión abdominal generalizada.", t:"Meteorismo"},
{cat:"Digestivo", d:"Ruidos hidroaéreos intestinales aumentados de intensidad y frecuencia, audibles a veces sin estetoscopio.", t:"Borborigmos"},

// ===== Nefrourinario =====
{cat:"Nefrourinario", d:"Sistema compuesto por los riñones, las vías urinarias y la vejiga. Sus funciones principales incluyen la filtración de la sangre, la eliminación de desechos y el mantenimiento del equilibrio hidroelectrolítico.", t:"Sistema nefrourinario"},
{cat:"Nefrourinario", d:"El parénquima renal en sí no duele; el dolor surge de la irritación de la cápsula renal, la pelvis, la región perirrenal o los nervios cercanos. Se sitúa habitualmente en la región lumbar o en la parte superior del hemiabdomen.", t:"Dolor de origen renal"},
{cat:"Nefrourinario", d:"Tipo de dolor renal con sensación de pesadez (ej.: riñón poliquístico, tumores).", t:"Dolor renal continuo"},
{cat:"Nefrourinario", d:"Tipo de dolor renal de intensidad variable con exacerbaciones por espasmos ureterales, frecuentemente por cálculos. Incluye variantes como el cólico frustro o la crisis de Dietl (por ptosis renal).", t:"Cólico renal"},
{cat:"Nefrourinario", d:"Variante de cólico renal que se produce por ptosis renal.", t:"Crisis de Dietl"},
{cat:"Nefrourinario", d:"Comienzo del dolor renal: puede ser agudo (aparición brusca) o crónico (carácter sordo y persistente).", t:"Comienzo del dolor renal"},
{cat:"Nefrourinario", d:"Irradiación del dolor renal: descendente (hacia los genitales) o ascendente (desde la pelvis a la zona lumbar).", t:"Irradiación del dolor renal"},
{cat:"Nefrourinario", d:"Signos asociados al dolor renal: edemas, hipertensión arterial, náuseas, vómitos y manifestaciones neuro-vegetativas (taquicardia, sudoración).", t:"Signos asociados al dolor renal"},
{cat:"Nefrourinario", d:"Cantidad de orina en 24 horas; el valor normal es entre 800 y 1500 cc.", t:"Diuresis"},
{cat:"Nefrourinario", d:"Modificación cuantitativa de la diuresis: más de 1500 cc.", t:"Poliuria"},
{cat:"Nefrourinario", d:"Modificación cuantitativa de la diuresis: menos de 800 cc.", t:"Oliguria"},
{cat:"Nefrourinario", d:"Modificación cuantitativa de la diuresis: menos de 400 cc.", t:"Oligo-anuria"},
{cat:"Nefrourinario", d:"Cese total de la secreción de orina.", t:"Anuria"},
{cat:"Nefrourinario", d:"Modificación del ritmo urinario: inversión del ritmo (se orina más de noche que de día).", t:"Nicturia"},
{cat:"Nefrourinario", d:"Modificación del ritmo urinario: aumento del número de micciones; puede ser obligada por poliuria o verdadera por cistitis.", t:"Polaquiuria"},
{cat:"Nefrourinario", d:"Emisión involuntaria de orina durante el sueño; es anormal después de los 4 años.", t:"Enuresis"},
{cat:"Nefrourinario", d:"Demora en eliminar el agua ingerida.", t:"Opsiuria"},
{cat:"Nefrourinario", d:"Modificación de la micción: dolor o ardor al orinar.", t:"Disuria"},
{cat:"Nefrourinario", d:"Modificación de la micción: emisión penosa de orina gota a gota.", t:"Estranguria"},
{cat:"Nefrourinario", d:"Modificación de la micción: imposibilidad de retener la orina.", t:"Incontinencia"},
{cat:"Nefrourinario", d:"Incapacidad para eliminar la orina, pudiendo formar un \"globo vesical\".", t:"Retención urinaria"},
{cat:"Nefrourinario", d:"Necesidad imperiosa y frecuente de orinar.", t:"Tenesmo vesical"},
{cat:"Nefrourinario", d:"El color de la orina va de ámbar pálido (normal) a rojo (hematuria), lechoso (grasa) o coluria (pigmentos biliares).", t:"Color de la orina"},
{cat:"Nefrourinario", d:"Presencia de pus en la orina.", t:"Piuria"},
{cat:"Nefrourinario", d:"Presencia de bacterias en la orina.", t:"Bacteriuria"},
{cat:"Nefrourinario", d:"Presencia de sangre en la orina (color rojo). Se clasifica según el momento de aparición: uretral (inicio), vesical (final) o renal (toda la micción).", t:"Hematuria"},
{cat:"Nefrourinario", d:"Hematuria que aparece al inicio de la micción.", t:"Hematuria uretral"},
{cat:"Nefrourinario", d:"Hematuria que aparece al final de la micción.", t:"Hematuria vesical"},
{cat:"Nefrourinario", d:"Hematuria presente durante toda la micción.", t:"Hematuria renal"},
{cat:"Nefrourinario", d:"Si la espuma de la orina es abundante y persistente, indica proteinuria o glucosuria.", t:"Espuma en la orina"},
{cat:"Nefrourinario", d:"El olor amoniacal sugiere infección, mientras que el fétido puede indicar cáncer de vejiga.", t:"Olor de la orina"},
{cat:"Nefrourinario", d:"El valor normal de la densidad urinaria es 1015 a 1025. La densidad baja es típica de la insuficiencia renal crónica.", t:"Hipostenuria"},

// ===== Gineco-obstétrico =====
{cat:"Gineco-obstétrico", d:"Inicio del desarrollo mamario; constituye el primer signo puberal femenino.", t:"Telarca"},
{cat:"Gineco-obstétrico", d:"Aparición del vello pubiano.", t:"Pubarca"},
{cat:"Gineco-obstétrico", d:"Aparición del vello axilar.", t:"Axilarca"},
{cat:"Gineco-obstétrico", d:"Primera menstruación.", t:"Menarca"},
{cat:"Gineco-obstétrico", d:"La menstruación normal presenta intervalos entre 21 y 35 días y una duración entre 2 y 7 días.", t:"Menstruación normal"},
{cat:"Gineco-obstétrico", d:"Cualquier sangrado que difiere de lo normal en frecuencia, regularidad o volumen.", t:"Sangrado uterino anormal (SUA)"},
{cat:"Gineco-obstétrico", d:"SUA según el ritmo: intervalos menores de 21 días.", t:"Polimenorrea"},
{cat:"Gineco-obstétrico", d:"SUA según el ritmo: intervalos entre 35 y 90 días.", t:"Oligomenorrea"},
{cat:"Gineco-obstétrico", d:"SUA según el ritmo: ausencia de menstruación durante más de 3 meses.", t:"Amenorrea"},
{cat:"Gineco-obstétrico", d:"SUA según la cantidad: aumento del volumen del sangrado.", t:"Hipermenorrea"},
{cat:"Gineco-obstétrico", d:"SUA según la duración: menstruación con duración mayor de 7 días.", t:"Menorragia"},
{cat:"Gineco-obstétrico", d:"SUA según la cantidad: sangrado escaso.", t:"Hipomenorrea"},
{cat:"Gineco-obstétrico", d:"Sangrado no coincidente con el ciclo menstrual.", t:"Metrorragia"},
{cat:"Gineco-obstétrico", d:"Menstruación dolorosa.", t:"Dismenorrea"},
{cat:"Gineco-obstétrico", d:"Causas de SUA: pólipo, adenomiosis, leiomioma y malignidad.", t:"PALM"},
{cat:"Gineco-obstétrico", d:"Causas de SUA: coagulopatía, trastornos ovulatorios, alteraciones endometriales, causas iatrogénicas y causas no clasificadas.", t:"COEIN"},
{cat:"Gineco-obstétrico", d:"La gestación normal tiene una duración de 38 a 42 semanas.", t:"Duración de la gestación normal"},
{cat:"Gineco-obstétrico", d:"Se calcula mediante: FUM + 10 días − 3 meses.", t:"Fecha probable de parto (FPP)"},
{cat:"Gineco-obstétrico", d:"Paridad: nunca ha tenido un parto.", t:"Nulípara"},
{cat:"Gineco-obstétrico", d:"Paridad: ha tenido más de un parto viable.", t:"Multípara"},
{cat:"Gineco-obstétrico", d:"Paridad: mujer embarazada.", t:"Grávida"},
{cat:"Gineco-obstétrico", d:"Patología del embarazo: hipertensión arterial y proteinuria después de la semana 20.", t:"Preeclampsia"},
{cat:"Gineco-obstétrico", d:"Patología del embarazo: aparición de convulsiones asociadas a la preeclampsia.", t:"Eclampsia"},
{cat:"Gineco-obstétrico", d:"Interrupción del embarazo antes de las 20 semanas o con un peso fetal menor de 500 g. Se distingue entre IVE e ILE.", t:"Aborto"},
{cat:"Gineco-obstétrico", d:"Una de las dos modalidades de interrupción del embarazo que distingue el resumen (la otra es la legal).", t:"Interrupción Voluntaria del Embarazo (IVE)"}, // REVISAR: el resumen solo da el nombre de la sigla, sin definición
{cat:"Gineco-obstétrico", d:"Una de las dos modalidades de interrupción del embarazo que distingue el resumen (la otra es la voluntaria).", t:"Interrupción Legal del Embarazo (ILE)"}, // REVISAR: el resumen solo da el nombre de la sigla, sin definición
{cat:"Gineco-obstétrico", d:"Período de 60 días posteriores al parto durante el cual el organismo retorna progresivamente a su estado previo.", t:"Puerperio"},
{cat:"Gineco-obstétrico", d:"Método anticonceptivo (preservativos): son los únicos que disminuyen el riesgo de ITS.", t:"Métodos de barrera"},
{cat:"Gineco-obstétrico", d:"Método anticonceptivo: DIU de cobre y DIU hormonal.", t:"LARC"},
{cat:"Gineco-obstétrico", d:"Método anticonceptivo quirúrgico.", t:"Ligadura tubaria"}, // REVISAR: el resumen solo la lista como método quirúrgico, sin más definición
{cat:"Gineco-obstétrico", d:"Método anticonceptivo quirúrgico.", t:"Vasectomía"}, // REVISAR: el resumen solo la lista como método quirúrgico, sin más definición
{cat:"Gineco-obstétrico", d:"Patología frecuente: flujo y prurito.", t:"Vaginitis"},
{cat:"Gineco-obstétrico", d:"Tumor benigno más frecuente.", t:"Mioma"},
{cat:"Gineco-obstétrico", d:"Descenso de los órganos pélvicos.", t:"Prolapso genital"},
{cat:"Gineco-obstétrico", d:"Inflamación de la mama, frecuente durante la lactancia.", t:"Mastitis"},
{cat:"Gineco-obstétrico", d:"Cirugía: extirpación del útero.", t:"Histerectomía"},
{cat:"Gineco-obstétrico", d:"Cirugía: extirpación de la mama.", t:"Mastectomía"},

// ===== Sistema nervioso =====
{cat:"Sistema nervioso", d:"Alteraciones del olfato (I par craneal) que modifican la intensidad con la que se perciben los olores.", t:"Alteraciones cuantitativas del olfato"},
{cat:"Sistema nervioso", d:"Alteraciones del olfato (I par craneal) que alteran la percepción del olor.", t:"Alteraciones cualitativas del olfato"},
{cat:"Sistema nervioso", d:"Pérdida total del olfato.", t:"Anosmia"},
{cat:"Sistema nervioso", d:"Disminución parcial de la capacidad para percibir olores.", t:"Hiposmia"},
{cat:"Sistema nervioso", d:"Aumento exagerado de la sensibilidad olfatoria.", t:"Hiperosmia"},
{cat:"Sistema nervioso", d:"Percepción distorsionada de un olor.", t:"Parosmia"},
{cat:"Sistema nervioso", d:"Percepción de olores desagradables o nauseabundos.", t:"Cacosmia"},
{cat:"Sistema nervioso", d:"Percepción de olores en ausencia de un estímulo real.", t:"Alucinaciones olfatorias"},
{cat:"Sistema nervioso", d:"Alteraciones de la visión (II par craneal): pueden afectar la agudeza visual, el campo visual o la percepción de los colores.", t:"Alteraciones de la visión"},
{cat:"Sistema nervioso", d:"Pérdida total de la visión.", t:"Amaurosis"},
{cat:"Sistema nervioso", d:"Pérdida transitoria y unilateral de la visión asociada a isquemia.", t:"Amaurosis fugaz"},
{cat:"Sistema nervioso", d:"Disminución de la agudeza visual sin lesión orgánica evidente.", t:"Ambliopía"},
{cat:"Sistema nervioso", d:"Dificultad para la visión nocturna.", t:"Hemeralopía"}, // REVISAR: el resumen define hemeralopía = visión nocturna y nictalopía = visión diurna; en otras fuentes se invierten
{cat:"Sistema nervioso", d:"Dificultad para la visión diurna.", t:"Nictalopía"}, // REVISAR: ver nota de hemeralopía
{cat:"Sistema nervioso", d:"Área de pérdida parcial del campo visual.", t:"Escotoma"},
{cat:"Sistema nervioso", d:"Escotoma que corresponde al punto ciego fisiológico.", t:"Escotoma negativo"},
{cat:"Sistema nervioso", d:"Escotoma en el que el paciente percibe una mancha oscura dentro del campo visual.", t:"Escotoma positivo"},
{cat:"Sistema nervioso", d:"Pérdida de la mitad del campo visual; puede ser homónima o heterónoma.", t:"Hemianopsia"},
{cat:"Sistema nervioso", d:"Pérdida de un cuarto del campo visual.", t:"Cuadrantopsia"},
{cat:"Sistema nervioso", d:"Alteración de la percepción de los colores.", t:"Discromatopsia"},
{cat:"Sistema nervioso", d:"Ausencia de percepción de los colores.", t:"Acromatopsia"},
{cat:"Sistema nervioso", d:"Percepción alterada de los colores.", t:"Metacromatopsia"},
{cat:"Sistema nervioso", d:"Percepción de un único color.", t:"Monocromatopsia"},
{cat:"Sistema nervioso", d:"Alteración de la motilidad ocular (III, IV y VI pares craneales): visión doble.", t:"Diplopía"},
{cat:"Sistema nervioso", d:"Desviación ocular característica de la lesión del III par craneal.", t:"Estrabismo externo"},
{cat:"Sistema nervioso", d:"Desviación ocular característica de la lesión del VI par craneal.", t:"Estrabismo interno convergente"},
{cat:"Sistema nervioso", d:"Caída del párpado superior (alteración de la motilidad ocular).", t:"Ptosis palpebral (neurológica)"},
{cat:"Sistema nervioso", d:"Desigualdad en el tamaño de las pupilas.", t:"Anisocoria"},
{cat:"Sistema nervioso", d:"Dilatación pupilar mayor de 4 mm.", t:"Midriasis"},
{cat:"Sistema nervioso", d:"Contracción pupilar menor de 2 mm.", t:"Miosis"},
{cat:"Sistema nervioso", d:"Alteración de la forma de la pupila.", t:"Discoria"},
{cat:"Sistema nervioso", d:"Oscilaciones rítmicas del diámetro pupilar frente a la luz.", t:"Hippus fisiológico"},
{cat:"Sistema nervioso", d:"V par craneal: dolor localizado en el trayecto de un nervio.", t:"Neuralgia"},
{cat:"Sistema nervioso", d:"V par craneal: dificultad para abrir la boca por contractura del músculo masetero.", t:"Trismo (V par craneal)"},
{cat:"Sistema nervioso", d:"VII par craneal: afecta la mitad inferior de la cara.", t:"Parálisis facial central"},
{cat:"Sistema nervioso", d:"VII par craneal: compromete tanto la mitad superior como la inferior de la cara.", t:"Parálisis facial periférica"},
{cat:"Sistema nervioso", d:"VII par craneal: imposibilidad de cerrar completamente el ojo.", t:"Lagoftalmo"},
{cat:"Sistema nervioso", d:"VII par craneal: lagrimeo.", t:"Epífora"},
{cat:"Sistema nervioso", d:"VII par craneal: contracciones involuntarias de un lado de la cara.", t:"Hemiespasmo facial"},
{cat:"Sistema nervioso", d:"VIII par craneal, alteración auditiva: pérdida total de la audición.", t:"Anacusia"},
{cat:"Sistema nervioso", d:"VIII par craneal, alteración auditiva: disminución de la audición.", t:"Hipoacusia"},
{cat:"Sistema nervioso", d:"VIII par craneal, alteración auditiva: sensibilidad exagerada a los sonidos.", t:"Hiperacusia"},
{cat:"Sistema nervioso", d:"VIII par craneal, alteración auditiva: mejor audición en ambientes ruidosos.", t:"Paracusia"},
{cat:"Sistema nervioso", d:"VIII par craneal, alteración auditiva: percepción de zumbidos u otros sonidos sin un estímulo externo.", t:"Acúfenos"},
{cat:"Sistema nervioso", d:"Alteración vestibular: sensación de giro del propio cuerpo o del ambiente.", t:"Vértigo"},
{cat:"Sistema nervioso", d:"Alteración vestibular: sensación inespecífica de inestabilidad.", t:"Mareo"},
{cat:"Sistema nervioso", d:"Alteración vestibular: movimiento ocular involuntario, rítmico y repetitivo.", t:"Nistagmo"},
{cat:"Sistema nervioso", d:"Alteración del gusto (IX-X-XI-XII): pérdida del gusto.", t:"Ageusia"},
{cat:"Sistema nervioso", d:"Alteración del gusto: disminución del gusto.", t:"Hipogeusia"},
{cat:"Sistema nervioso", d:"Alteración del gusto: percepción distorsionada del gusto.", t:"Parageusia"},
{cat:"Sistema nervioso", d:"Alteración de la deglución: dificultad para deglutir.", t:"Disfagia (neurológica)"},
{cat:"Sistema nervioso", d:"Alteración de la voz: tonalidad nasal.", t:"Rinolalia"},
{cat:"Sistema nervioso", d:"Alteración de la voz: emisión simultánea de dos tonos de voz.", t:"Voz bitonal"},
{cat:"Sistema nervioso", d:"Alteración de la voz: alteración de la calidad o el tono de la voz.", t:"Disfonía (neurológica)"},
{cat:"Sistema nervioso", d:"Alteración de la voz: pérdida total de la voz.", t:"Afonía (neurológica)"},
{cat:"Sistema nervioso", d:"Marcha normal.", t:"Eubasia"},
{cat:"Sistema nervioso", d:"Marcha lenta con pasos cortos.", t:"Bradibasia"},
{cat:"Sistema nervioso", d:"Marcha patológica.", t:"Disbasia"},
{cat:"Sistema nervioso", d:"Tono muscular: aumento.", t:"Hipertonía"},
{cat:"Sistema nervioso", d:"Tono muscular: disminución.", t:"Hipotonía"},
{cat:"Sistema nervioso", d:"Tono muscular: ausencia.", t:"Atonía"},
{cat:"Sistema nervioso", d:"Tono muscular: oscilación.", t:"Distonía"},
{cat:"Sistema nervioso", d:"Fuerza muscular: pérdida total de la fuerza.", t:"Parálisis"},
{cat:"Sistema nervioso", d:"Fuerza muscular: disminución parcial de la fuerza.", t:"Paresia"},
{cat:"Sistema nervioso", d:"Términos para clasificar la pérdida de fuerza según su distribución: hemiplejia, monoplejia, paraplejia y cuadriplejia.", t:"Hemiplejia / Monoplejia / Paraplejia / Cuadriplejia"}, // REVISAR: el resumen solo enumera los términos, sin definir cada uno
{cat:"Sistema nervioso", d:"Movimientos involuntarios bruscos, breves y súbitos.", t:"Mioclonías"},
{cat:"Sistema nervioso", d:"Movimiento involuntario rítmico.", t:"Temblor"},
{cat:"Sistema nervioso", d:"Movimientos involuntarios amplios, rápidos y bruscos.", t:"Movimientos coreicos"},
{cat:"Sistema nervioso", d:"Movimientos involuntarios lentos y ondulantes.", t:"Movimientos atetósicos"},
{cat:"Sistema nervioso", d:"Movimientos involuntarios repetitivos.", t:"Tics"},
{cat:"Sistema nervioso", d:"Convulsiones con contracción muscular sostenida.", t:"Convulsiones tónicas"},
{cat:"Sistema nervioso", d:"Convulsiones con contracciones musculares repetidas.", t:"Convulsiones clónicas"},
{cat:"Sistema nervioso", d:"Ausencia de sensibilidad.", t:"Anestesia"},
{cat:"Sistema nervioso", d:"Disminución de la sensibilidad.", t:"Hipoestesia"},
{cat:"Sistema nervioso", d:"Aumento de la sensibilidad.", t:"Hiperestesia"},
{cat:"Sistema nervioso", d:"Sensación anormal como hormigueo o adormecimiento.", t:"Parestesias"},
{cat:"Sistema nervioso", d:"Sensibilidad a la presión.", t:"Barestesia"},
{cat:"Sistema nervioso", d:"Capacidad para reconocer el peso de un objeto.", t:"Barognosia"},
{cat:"Sistema nervioso", d:"Sensibilidad vibratoria.", t:"Palestesia"},
{cat:"Sistema nervioso", d:"Capacidad para reconocer la posición de las distintas partes del cuerpo.", t:"Batiestesia"},
{cat:"Sistema nervioso", d:"Percepción del movimiento.", t:"Cinestesia"},
{cat:"Sistema nervioso", d:"Capacidad para reconocer un objeto mediante el tacto.", t:"Esterognosia"},
{cat:"Sistema nervioso", d:"Función mental superior: capacidad para ejecutar actos motores aprendidos.", t:"Praxia"},
{cat:"Sistema nervioso", d:"Pérdida de la capacidad para ejecutar actos motores aprendidos.", t:"Apraxia"},
{cat:"Sistema nervioso", d:"Función mental superior: capacidad para reconocer estímulos sensoriales.", t:"Gnosia"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer estímulos sensoriales.", t:"Agnosia"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer partes del propio cuerpo.", t:"Agnosia corporal"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer la propia enfermedad.", t:"Anosognosia"},
{cat:"Sistema nervioso", d:"Incapacidad para reconocer el cuerpo como un todo.", t:"Autotopagnosia"},
{cat:"Sistema nervioso", d:"Ausencia de expresión facial.", t:"Amimia"},
{cat:"Sistema nervioso", d:"Alteración en el cálculo de la distancia de los movimientos.", t:"Dismetría"},
{cat:"Sistema nervioso", d:"Repetición innecesaria de gestos o conductas.", t:"Estereotipia"},
{cat:"Sistema nervioso", d:"Estado máximo de alteración de la conciencia.", t:"Coma"}
];
